### ISSUE TITLE
No installation script nor update path for version "X"

### ISSUE THREAD

**Issue by vicpermir** [timescale/timescaledb#1065]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version: 10.6
 - TimescaleDB version: 1.2.1
 - Installation method: Windows .zip installation

**Describe the bug**
When I execute the command `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` I get the following error:
`SQL Error [22023]: ERROR: extension "timescaledb" has no installation script nor update path for version "1.2.0"`
Note the version he is complaining about: **1.2.0** (but I downloaded **1.2.1**, which is latest currently)

**To Reproduce**
1. Fresh installation of timescaledb
2. Follow the steps on the "[getting-started](https://docs.timescale.com/v1.2/getting-started/installation/windows/installation-windows)" doc tutorial
3. Reach the "CREATE EXTENSION..." step

**Expected behavior**
Extension to be created normally

**Actual behavior**
PostgreSQL throws an error [22023]

**Workaround**
I was able to create the extension by forcing the version that was actually installed (1.2.1) like so:
`CREATE EXTENSION IF NOT EXISTS timescaledb WITH VERSION '1.2.1' CASCADE;`

**Comment by mfreed** [comment]
Hi @vicpermir :

Can you confirm that you installed `timescaledb-postgresql-10`, and not an individual "point" release like `timescaledb-1.2.0-postgresql-10`?

Thanks!

**Comment by vicpermir** [comment]
Hi @mfreed  

The file I downloaded for windows/zip installation is "`timescaledb-postgresql-10_1.2.1-windows-amd64.zip`", although I just clicked on the link the tutorial provides ("`.zip file for your PostgreSQL version`", right under **Build & Install**).

Thank you !

**Comment by catchem99** [comment]
I'm following the same doc and having the same problem `ERROR: extension "timescaledb" has no installation script nor update path for version "1.2.0"` I've tried the workaround `CREATE EXTENSION IF NOT EXISTS timescaledb WITH VERSION '1.2.1' CASCADE;` but the same thing happened anyway.

Is it normal if I use `SELECT * FROM pg_extension` there's no timescaledb string in there?

**Comment by vicpermir** [comment]
Hi @catchem99 

It seems you did not install the extension correctly, you should see a row for **timescaledb** when you execute `SELECT * FROM pg_extension` .

Did you edit your postgresql.conf to preload the library? (remember to restart the postgresql service after that is done)

**Comment by catchem99** [comment]
Thanks for the reply @vicpermir, I'm using timescaledb's `timescaledb-tune.exe' and I've double checked the postgresql.conf.

But I've found the solution! In my case, timescale's `setup.exe` failed to copy `timescaledb--1.2.1.sql` to `postgresql\share\extension` while the other files such as `timescaledb--0.1.0--1.2.1.sql` is on the directory.

After I copied it manually, the setup works as expected.

**Comment by RobAtticus** [comment]
Thanks for reporting this @catchem99, I am not sure why it did not install that file, but the installer was swallowing errors during copy which is an issue. I've updated the installer so that if it fails to copy a file in the future it'll cause an error.

**Comment by amarRajp** [comment]
OS: Windows server 2008 R2 standard x64
PostgreSQL version: 10.0
TimescaleDB version: timescaledb-postgresql-10_1.2.1-windows-amd64
Installation method: Windows .zip installation

When I execute the command CREATE EXTENSION IF NOT EXISTS 
; I get the following error:
ERROR:  extension "timescaledb" has no installation script nor update path for version "1.2.0"
SQL state: 22023


i also tried another option like-
CREATE EXTENSION IF NOT EXISTS timescaledb WITH VERSION '1.2.1' CASCADE;

then ; I get the following error:
ERROR:  extension "timescaledb" does not support postgres version 10.0
SQL state: 0A000

**Comment by amarRajp** [comment]
> Thanks for the reply @vicpermir, I'm using timescaledb's `timescaledb-tune.exe' and I've double checked the postgresql.conf.
> 
> But I've found the solution! In my case, timescale's `setup.exe` failed to copy `timescaledb--1.2.1.sql` to `postgresql\share\extension` while the other files such as `timescaledb--0.1.0--1.2.1.sql` is on the directory.
> 
> After I copied it manually, the setup works as expected.

@ catchem99  same problem  i got, your solution also work for me.

**Comment by mfreed** [comment]
Closing this issue as I believed fixed; please re-open if continue to have problems.

**Comment by justintime4tea** [comment]
I know this issue is in the context of Windows but I've ran into the same issue in a Linux context and this was the closest issue I could find that described my issue. I know this issue is closed but I wanted to comment in the event someone finds this issue like I did and is experiencing a similar issue as I am - Linux installation of timescale where a timescaledb extension version other than that which is installed is "default" when running `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE`. 

The TLDR is that the version used by "default" when running `CREATE EXTENTION` comes from a "control" file and if the package that installs this "control" file isn't "in the same version" as the other timescaledb packages, you could get this same issue of not finding the installation script.

In my case I was basing a container image off of the `crunchy-postgres` container image and ran my own `microdnf install` commands to setup timescaledb. In my case, I was installing two specific packages but was missing a third package:

```
microdnf install -y timescaledb-2-postgresql-${TIMESCALEDB_VERSION}
microdnf install -y timescaledb-toolkit-postgresql-${TIMESCALEDB_TOOLKIT_VERSION}
```

There was another package that had been being installed, `timescaledb-2-loader-postgresql`, and this package contain "control" files. The `timescaledb.control` file in this package contains the "default" version for the _latest_ but I was installing an older specific version. The solution for me was to add `timescaledb-2-loader-postgresql-${TIMESCALEDB_VERSION}` to install the appropriate "loader" package where the `timescaledb.control` file points to the proper "default" version. Afterwords `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE` works without specifying the specific version.
