### ISSUE TITLE
Apply custom constraint exclusion also to DELETE and UPDATE query types

### ISSUE THREAD

**Issue by consense** [timescale/timescaledb#1085]
**Relevant system information:**
 - OS: Ubuntu 16.04.5 LTS
 - PostgreSQL version 9.6
 - TimescaleDB version 1.2.1
 - Installation method: apt install via ansible role

**Describe the bug**

Deleting a single row (by composite-primary-key: uuid+timestamp) from a hypertable takes an unusual amount of time. (in the range of 100ms-500ms). When looking at EXPLAIN ANALYZE 99% of this seems to be spent in the planning phase:

```
EXPLAIN ANALYZE
DELETE FROM "myhypertablename" WHERE "uuid" = '9caeabf1-d045-4cce-adee-1382c47cb1ae' AND "time" = '2019-02-14 15:00:02.247'
```

query plan:

```
Delete on myhypertablename  (cost=0.00..2.63 rows=2 width=6) (actual time=0.095..0.095 rows=0 loops=1)
  Delete on myhypertablename
  Delete on _hyper_2_2805_chunk
  ->  Seq Scan on myhypertablename  (cost=0.00..0.00 rows=1 width=6) (actual time=0.010..0.010 rows=0 loops=1)
        Filter: ((uuid = '9caeabf1-d045-4cce-adee-1382c47cb1ae'::uuid) AND ("time" = '2019-02-14 15:00:02.247+01'::timestamp with time zone))
  ->  Index Scan using "2805_14741_myhypertablename_pkey" on _hyper_2_2805_chunk  (cost=0.41..2.63 rows=1 width=6) (actual time=0.036..0.037 rows=1 loops=1)
        Index Cond: (("time" = '2019-02-14 15:00:02.247+01'::timestamp with time zone) AND (uuid = '9caeabf1-d045-4cce-adee-1382c47cb1ae'::uuid))
Planning time: 200.719 ms
Execution time: 0.181 ms
```

The table contains ~2.5million rows and shows following statistics:

```
SELECT * FROM timescaledb_information.hypertable;
table_schema    table_name    table_owner         num_dimensions      num_chunks    table_size    index_size    toast_size     total_size
public          myhypertablename    user_production     1                  411            693 MB        527 MB        3288 kB         1223 MB
```

Chunking interval is  `day`.

**Expected behavior**

Delete/update queries targeting an element by primary key (incl. timestamp) should not take more than 10ms for such a low amount of rows and chunks.

**Actual behavior**

See query plan above.
200ms spent in planning phase

**Additional context**

just for comparison, an analogous SELECT query which shows fine performance:

```
EXPLAIN ANALYZE
SELECT FROM "myhypertablename" WHERE "uuid" = '9caeabf1-d045-4cce-adee-1382c47cb1ae' AND "time" = '2019-02-14 15:00:02.247'
```

```
Append  (cost=0.00..2.63 rows=2 width=0) (actual time=0.027..0.027 rows=0 loops=1)
  ->  Seq Scan on myhypertablename  (cost=0.00..0.00 rows=1 width=0) (actual time=0.003..0.003 rows=0 loops=1)
        Filter: ((uuid = '9caeabf1-d045-4cce-adee-1382c47cb1ae'::uuid) AND ("time" = '2019-02-14 15:00:02.247+01'::timestamp with time zone))
  ->  Index Only Scan using "2805_14741_myhypertablename_pkey" on _hyper_2_2805_chunk  (cost=0.41..2.63 rows=1 width=0) (actual time=0.022..0.022 rows=0 loops=1)
        Index Cond: (("time" = '2019-02-14 15:00:02.247+01'::timestamp with time zone) AND (uuid = '9caeabf1-d045-4cce-adee-1382c47cb1ae'::uuid))
        Heap Fetches: 1
Planning time: 0.487 ms
Execution time: 0.067 ms
```

- VACUUM ANALYZE was done prior to executing above queries
- as discussed with @mfreed on slack, the measures described in https://blog.timescale.com/optimizing-queries-timescaledb-hypertables-with-partitions-postgresql-6366873a995d/ do not yet apply to non-SELECT queries. My hope would be to add corresponding constraints avoiding a full iteration of all chunks for DELETE/UPDATE using primary-key conditions.

**Comment by mfreed** [comment]
Thanks for the report @consense .  

To be clear, constraint exclusion does apply to DELETE/UPDATE, which is why the actual *execution* of the plan only touches a single chunk and takes ~200us.  

The planning issue is that Postgres itself stores statistics about chunks on disk, so if you have a lot of chunks, just the process of opening each of these chunks for planning (in order to exclude them with constraint exclusion!) can take a large amount of time.  That's what the blog post is about.

But that is rather semantics, as you really just care about making your request faster.  We hear the request!

**Comment by hughes-tech** [comment]
Hi.  Firstly, thanks for your work on the code.  It's great.  Can you tell me if there's been any progress on this issue?  We've been working around this bug since we started using tsdb for our data. Our tests showed a select on a particular condition returned data in about 2ms.  A delete with the same condition took 6,464ms !   Updates are just as bad.  And more importantly, the performance was getting worse every day as the data set grew.  Without the hacks we have in place tsdb isn't usable for use cases that include deletes or updates.  Is this issue on anyone's radar?

**Comment by svenklemm** [comment]
This situation should be much better in more recent postgres versions. For the types of queries you are using plan time constraint exclusion should work. Feel free to reopen if you can reproduce with more recent version.

**Comment by hostops** [comment]
Hello!
I do not think this problem is fixed yet. 
```sql
EXPLAIN (ANALYZE,BUFFERS,TIMING) DELETE FROM signal WHERE id = 1623497891073 AND time BETWEEN '2021-07-14 08:20:00' AND '2021-07-14 08:30:00';
                                                                                         QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Delete on signal  (cost=0.00..2.65 rows=2 width=6) (actual time=0.111..0.112 rows=0 loops=1)
   Delete on signal
   Delete on _hyper_1_2101_chunk signal_1
   Buffers: shared hit=15
   ->  Seq Scan on signal  (cost=0.00..0.00 rows=1 width=6) (actual time=0.017..0.017 rows=0 loops=1)
         Filter: (("time" >= '2021-07-14 08:20:00'::timestamp without time zone) AND ("time" <= '2021-07-14 08:30:00'::timestamp without time zone) AND (id = '1623497891073'::bigint))
   ->  Index Scan using _hyper_1_2101_chunk_signal_time_id_key on _hyper_1_2101_chunk signal_1  (cost=0.43..2.65 rows=1 width=6) (actual time=0.030..0.050 rows=6 loops=1)
         Index Cond: ((id = '1623497891073'::bigint) AND ("time" >= '2021-07-14 08:20:00'::timestamp without time zone) AND ("time" <= '2021-07-14 08:30:00'::timestamp without time zone))
         Buffers: shared hit=9
 Planning:
   Buffers: shared hit=67145
 Planning Time: 2566.287 ms
 Execution Time: 0.200 ms
(13 rows)
```

I get similar results when modified queries:
```sql
DELETE FROM signal WHERE id = 1623497891073 AND time >= '2021-07-14 08:20:00' AND time < '2021-07-14 08:30:00';
DELETE FROM signal WHERE false;
DELETE FROM signal WHERE id = 1623497891073 AND time = '2021-07-14 08:30:00';
DELETE FROM signal WHERE time = '2021-07-14 08:30:00';
...
```

Query plan for select:
```sql
EXPLAIN (ANALYZE,BUFFERS,TIMING) SELECT * FROM signal WHERE id = 1623497891073 AND time BETWEEN '2021-07-14 08:20:00' AND '2021-07-14 08:30:00';
                                                                                      QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using _hyper_1_2101_chunk_signal_time_id_key on _hyper_1_2101_chunk  (cost=0.43..2.65 rows=1 width=24) (actual time=0.015..0.031 rows=6 loops=1)
   Index Cond: ((id = '1623497891073'::bigint) AND ("time" >= '2021-07-14 08:20:00'::timestamp without time zone) AND ("time" <= '2021-07-14 08:30:00'::timestamp without time zone))
   Buffers: shared hit=9 dirtied=4
 Planning:
   Buffers: shared hit=47
 Planning Time: 0.536 ms
 Execution Time: 0.042 ms
(7 rows)
```
In this example, we are trying to delete only few records.
Chunk interval is 1 day.
We have cca 70Gi of data, mostly in this table.
```sql
SELECT * FROM timescaledb_information.hypertables;
 hypertable_schema | hypertable_name |   owner   | num_dimensions | num_chunks | compression_enabled | is_distributed | replication_factor | data_nodes | tablespaces
-------------------+-----------------+-----------+----------------+------------+---------------------+----------------+--------------------+------------+-------------
 public            | signal          | timestore |              1 |       2580 | f                   | f              |                    |            |
```
We use timescale-ha setup (2 instances) in Kubernetes with this image: timescale/timescaledb-ha:pg13.3-ts2.3.1-latest.
This query planning time is a huge problem for us since it also causes problems with OOM since we cannot disable overcommit in Kubernetes. This OOM problem should be rare, but this `DELETE` statements cause us a lot of problems. 
Is there any workaround we can do to speed up those `DELETE` queries
