### ISSUE TITLE
Creating a unique key on a non-partitioning column

### ISSUE THREAD

**Issue by mashaalmemon** [timescale/timescaledb#1120]
I have a table:

```sql
-- Table Definition ----------------------------------------------

CREATE TABLE schema.chat_action_logs (
    id uuid PRIMARY KEY,
    ts timestamp with time zone NOT NULL DEFAULT now(),
    chat_id uuid NOT NULL (null),
    log_entry jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT chat_action_logs_ts_chat_id_unique UNIQUE (ts, chat_id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX chat_action_logs_pkey ON schema.chat_action_logs(id uuid_ops);
CREATE UNIQUE INDEX chat_action_logs_ts_chat_id_unique ON schema.chat_action_logs(ts timestamptz_ops,chat_id uuid_ops);
```

I found would like to partition the table but not clear how. When I try to partition on 'ts' I get this error:

```sql
ERROR: cannot create a unique index without the column "ts" (used in partitioning)
```

As you can see, 'ts' itself is not a unique key, but 'ts'+'chat_id' is a composite unique key.

**Comment by mfreed** [comment]
Problem is the definition of primary key on `uuid` and the unique index on `uuid_ops`.  All UNIQUE keys/indexes need to include all partitioning column(s), here `ts`.

See the *Tip* here:  https://docs.timescale.com/v1.2/using-timescaledb/schema-management#indexing-best-practices

**Comment by mashaalmemon** [comment]
To be clear: 

- the primary key, which is a unique key, must include `ts` in it?  Correct? 
- And every unique key requires it, even if not necessary for the queries that depend on it? So I can't ensure uniqueness on a key that is not inclusive of `ts` because it is not allowed? 
- For unique keys, is `ts` required to be the first key or in any particular position of the unique key?

**Comment by mfreed** [comment]
If you are partitioning by `ts`:

* Any unique key (including any primary key) must include `ts`.  Most people don't actually define primary/unique keys for their hypertables.
* `ts` can be in any position in the composite key, it does not need to be first.

This is because we don't build global lookup structures other than the partitioning, which is disjoint.  So we achieve a unique `ts` because it first gets uniqueness because of the disjointness of partitioning, then because its declared unique within the/each local partitioning.
