### ISSUE TITLE
`TRUNCATE TABLE` deletes data but does not remove underlying chunks

### ISSUE THREAD

**Issue by abrkn** [timescale/timescaledb#116]
I experienced some odd behavior after running `TRUNCATE TABLE` on a table that has a hyper table. I didn't have time to investigate at the time and re-created the table.

**Comment by olofr** [comment]
Hi, thanks for reporting this. When I truncate an hypertable, the existing chunks are not removed although they are empty. Is this the behavior that you saw and found odd ? I think removing the empty chunks on truncate would be a better behavior and will look into fixing it.

**Comment by mfreed** [comment]
Hi @abrkn thanks for this feedback.

We'll look into more expected behavior for TRUNCATE in the future (i.e., delete the existing chunks), but for now, you can turn to our [drop_chunks](http://docs.timescale.com/api/api-timescaledb#drop_chunks) interface for the expected behavior:
```
 SELECT drop_chunks(NOW() + interval ‘1 year’, tablename)
```
drop_chunks deletes all chunks if all of their data are beyond the cut-off point (based on chunk constraints).  Here I'm just pushing out the leading edge by 1 year to just mean something "way in the future".  Not the prettiest interface, but can give you the functionality you want for now.

**Comment by mfreed** [comment]
Also, my testing confirms the same as @olofr :  after TRUNCATE, all the data is *deleted*, just that the existing chunks remain (but now are empty).

**Comment by mfreed** [comment]
Just a head's up:  PR currently being reviewed:   https://github.com/timescale/timescaledb/pull/131

**Comment by mfreed** [comment]
Fixed as part of 0.3.0 release (by @olofr).

https://github.com/timescale/timescaledb/releases/tag/0.3.0

**Comment by cercata** [comment]
> Hi @abrkn thanks for this feedback.
> 
> We'll look into more expected behavior for TRUNCATE in the future (i.e., delete the existing chunks), but for now, you can turn to our [drop_chunks](http://docs.timescale.com/api/api-timescaledb#drop_chunks) interface for the expected behavior:
> 
> ```
>  SELECT drop_chunks(NOW() + interval ‘1 year’, tablename)
> ```
> drop_chunks deletes all chunks if all of their data are beyond the cut-off point (based on chunk constraints). Here I'm just pushing out the leading edge by 1 year to just mean something "way in the future". Not the prettiest interface, but can give you the functionality you want for now.

This deletes all chunks ... I guess the drop_chunks() function has evolved since you write this, and the bahaviour has changed

**Comment by LRagji** [comment]
Just an update truncate table cascade fails with default config it is asking to increase the shared memory limit..
