### ISSUE TITLE
Upgrade path from regular tables to hypertables?

### ISSUE THREAD

**Issue by matthewmueller** [timescale/timescaledb#129]
Hey folks! I love what you're doing here and as soon as you get RDS and grafana support I'm jumping on board.

Until then, I'm wondering how hard it would be to just use a regular postgres table and then migrate later. 

I'm not really doing 150k metrics/second so the scale part of the equation I won't hit for a while, but I'd love a transparent upgrade path if/when I reach that. What I mean by a clean upgrade path is:

1. None of the SQL queries in my apps will change
2. Table columns are the same
3. Data migration doesn't take forever (though, maybe I don't even need to transfer data more than X days old)

My line of thinking is basically:

1. Make sure the required hyper table columns are present in a regular table
2. Take the functions provided in the sql/ directory
3. Use some sort of COPY IN function from postgres to copy from the regular table to a hypertable when I'm ready to migrate

Would that work? Or am I missing some issues? 😄

**Comment by mfreed** [comment]
The high bit is that you can "migrate" your data from your regular table to a hypertable using a path you suggest, which is basically COPYing your data from the regular to the hypertable.   More instructions here:

http://docs.timescale.com/getting-started/setup/migrate-from-postgresql#same-db

That said, Timescale offers more than just higher insert rates, and we've found this helpful for people with even smaller databases.  These include both special time-oriented functions useful at query time (and more we're adding), as well as faster queries in various scenarios due to our data model and specialized query optimizations.

Regarding Grafana issue, seems like this would be about postgres in general, not specific to TimescaleDB?  We're just waiting on Grafana to release their postgres connector, it's nothing specific to Timescale.  Their Postgres connector will work "out of the box".  And if you already are using Grafana via a REST interface, that should also work today.

Thanks!

**Comment by mfreed** [comment]
Also, if RDS is important for you, please send in a request to Amazon for Timescale.  See more here:

https://github.com/timescale/timescaledb/issues/65

**Comment by matthewmueller** [comment]
@mfreed thanks for the info! I have sent RDS an email about this. Finger crossed!

Definitely excited about timescaledb, just not ready/skilled enough to self-host a Postgres database 😄
