### ISSUE TITLE
100,000 hypertables

### ISSUE THREAD

**Issue by pjebs** [timescale/timescaledb#1291]
Can timescaledb support hundreds of thousands of hypertables in 1 db?

If not, is there an alternative way of structuring my db so I _can_ have 100 thousand hyper tables?

**Comment by mfreed** [comment]
@pjebs I'm not sure we've tested it to that (although certainly have had 10,000s of tables/chunks).  Can you explain a bit about your use case about why you want that number of hypertables?

**Comment by pjebs** [comment]
eg. Each table will be like a sheet in an Excel Spreadsheet. Potentially heaps of columns and many many rows.

**Comment by mfreed** [comment]
Hi @pjebs As I mentioned, we haven't tested this case, and would certainly welcome you reporting any findings.

Thanks!

**Comment by pjebs** [comment]
well we haven't got to that number of columns. We were hoping you would tell us it was okay before we commit to using timescaledb for our usecase.

**Comment by mfreed** [comment]
Hi @pjebs I would say that it's somewhat "off label" and hasn't been tested to that extent.  I more common scenario would be to use, say, one hypertable and a label, so that you can build the type of "sheets" you want via a select query.  If your sheets turn out to be quite small (how large are you thinking?), then less clear which aspects of Timescale you are using.

Easiest way to test is just to script a few lines of code that loops 100,000 times and in each iteraction, creates a hypertable...

**Comment by pjebs** [comment]
The problem with your suggestion is that all "sheets" would be expected to have the same number of columns and data types.

I'll give your test script a go.

**Comment by mfreed** [comment]
@pjebs Remember that TimescaleDB/PostgreSQL also supports JSON/JSONB fairly robustly, so a common schema has columns that are shared among all "sheets" (e.g., timestamp, sheet_type, etc.) then a JSON/JSON blob that varies by sheet_type.
