### ISSUE TITLE
Insert performance for very wide rows from Python

### ISSUE THREAD

**Issue by pdales** [timescale/timescaledb#1351]
**Relevant system information:**
 - OS:  Ubuntu 18
- 32 GB RAM, SSD, i9 (6 cores)
 - PostgreSQL version 11.4
 - TimescaleDB version: latest
 - Installation method: apt install

We are trying to use timescaleDB for our dataset which consists of 300 sensors recording at 6000 samples (single precision floats) per second. Our table is laid out with a time column plus a column for each sensor (301 total columns). Each second we insert 6000 rows of data using pyscopg2 execute values (inserts all 1.8 million samples in single block). On a high-end laptop the insertion time is taking 4.5 seconds therefore making it unusable for our real-time system. Is this insertion speed normal or are we missing something?

Here is the relevant lines of code:
```
cur.execute("CREATE TABLE sgrams (time TIMESTAMPTZ PRIMARY KEY NOT NULL);")
cur.execute("SELECT create_hypertable('sgrams', 'time');")

#....#

for name in column_names:
    cur.execute("ALTER TABLE sgrams ADD COLUMN %s REAL;" % (name))
#....#

# inserts 1 second of data (6000 rows of 300 values each), takes 4.5 seconds
execute_values(cur, 'INSERT INTO sgrams VALUES %s', data)

```

**Comment by mfreed** [comment]
Are there any additional indexes other than than what you shw (TimescaleDB's default indexes on time)?

Also, have you tried to insert the same directly from something like `psql`, where you have already built the string, and/or measure the insert performance that the database returns?  Our experience with some higher-level language libraries is that the bottleneck can often actually be the string marshaling on the client side, rather than the DB itself.

**Comment by WarriorOfWire** [comment]
Also, you're doing 60 INSERTs by that line.  Try changing your execute_values invocation to `execute_values(cur, 'sql stuff', data, page_size=len(data))`

**Comment by bboule** [comment]
@pdales just a quick follow up was wondering if this was still an open issue for you?

**Comment by pdales** [comment]
@bboule Sorry I did not do any further testing. Was limited for time and went for another solution. You can close the issue.
