### ISSUE TITLE
No update path from version dev version to version "1.3.2"

### ISSUE THREAD

**Issue by rwfnf** [timescale/timescaledb#1355]
It looks like I mistakenly installed a development versions previously (from master) and now, when trying to update with:
ALTER EXTENSION timescaledb UPDATE;

I get:
ERROR:  extension "timescaledb" has no update path from version "0.10.0-dev" to version "1.3.2"

What options do I have to upgrade?

Thanks!

**Comment by mfreed** [comment]
Hi @rwfnf Unfortunately upgrade paths require SQL scripts to ensure the safe and correct transformation from version to version (e.g., interfaces, internal schema changes, etc.), which is why we only provide them for tagged releases.

The best option here is to dump your data (potentially schema too if you want), then reload it into a new database (check out our parallel-copy tool).

Good luck!

**Comment by rwfnf** [comment]
Thank you, I'll do that.
