### ISSUE TITLE
Unique/primary keys within partitioning key?

### ISSUE THREAD

**Issue by thongpv87** [timescale/timescaledb#1419]
I have an `order` table:
```
CREATE TABLE order(
    order_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date_id INT REFERENCES date_dim(date_id) NOT NULL,
    region_id INT REFERENCES region_dim(region_id) NOT NULL,
    daily_order_id BIGINT NOT NULL,
    ts TIMESTAMPTZ NOT NULL,

    item TEXT NOT NULL,
    price numeric NOT NULL,
    qty INT NOT NULL
)
```
The candidate primary key of that table is  `(date_id, region_id, daily_order_id, ts)`. I want to create a hypertale on `ts` or `date_id` but timescale require that unique constraints use the partitioning keys as prefix. How can I do it without remove the surrogate key because I use it in other table as foreign key.

**Comment by mfreed** [comment]
Hi @thongpv3 I'm not sure I fully understand the question, but all primary keys (which imply unique constraints) require that they include the partitioning key(s).

So if you want to partition on `ts`, then any unique constraint/index must include `ts`.  We require that to ensure global uniqueness, as we don't otherwise build global indexes:  the global uniqueness arises from the chunks being disjoint on `ts`, and then *local* uniqueness on the composite `(ts, whatever)`.

**Comment by bboule** [comment]
@thongpv3  did @mfreed response answer your question?  Let us know if we can provide any additional information

**Comment by thongpv3** [comment]
Sorry, I forgot to respond the answer. So I can not use surrogate `order_id`, because it's primary key which imply unique constraint and it does not include partition key `ts`?

**Comment by erimatnor** [comment]
@thongpv87 The partitioning columns must include all primary keys.
