### ISSUE TITLE
show_chunks() and drop_chunks() throws a compressed hypertable error when no tables are specified.

### ISSUE THREAD

**Issue by bogdanul2003** [timescale/timescaledb#1535]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 11.4
 - TimescaleDB version (output of `\dx` in `psql`):1.5.1
 - Installation method: apt install

I enabled compression on one of the hypertables but now I'm unable to see how many chunks I have even though I didn't compress any chuncks yet. This is how I created the table:

```
CREATE TABLE rows_store
(
    row_cnt bigint NOT NULL,
    kernel_id int,
    pass_nr int,
    acq_id bigint,
    ch_meta json,
    ch_spectra real[],
    ch_image_path text,
    time_stamp bigint,
    UNIQUE(row_cnt)
);

CREATE INDEX idx_rows_store_acq_id 
ON rows_store(acq_id);

SELECT create_hypertable('rows_store', 'row_cnt', chunk_time_interval => 1000000);

ALTER TABLE rows_store SET (
  timescaledb.compress, 
  timescaledb.compress_segmentby = 'acq_id'
);
```

And here is the error:
```
# SELECT show_chunks(newer_than => 0);
ERROR:  cannot call chunk_get_chunks_in_time_range on a compressed hypertable
# SELECT drop_chunks(newer_than =>0);
ERROR:  cannot call chunk_get_chunks_in_time_range on a compressed hypertable
```

Is this the entended behaviour? In your [documentation](https://docs.timescale.com/latest/using-timescaledb/compression#advanced-usage) it looks like you can call `SELECT show_chunks('conditions', older_than => interval '3 days');` and then compress without any other quiries or errors.

**Comment by mfreed** [comment]
Appears to be duplicate https://github.com/timescale/timescaledb/issues/1519, but your information is also appreciated.

Cc: @gayyappan

**Comment by cevian** [comment]
This appears to be a separate error from #1519 or rather a case we didn't think of. Namely here show_chunks is working on all hypertables (no hypertable name is provided). Show_chunks should actually probably work on compressed hypertables. Drop chunks should error when run on a compressed_hypertable explicitly, but if no hypertable is specified should probably just silently ignore compressed_hypertables (because the drop on the uncompressed will drop the compressed as well...). This should be thought through more carefully and the interface should be reconsidered in 2.0.
