### ISSUE TITLE
Slow query planning time, fast execution time

### ISSUE THREAD

**Issue by byrman** [timescale/timescaledb#1636]
**Relevant system information:**
 - OS: Ubuntu 18.04.3 LTS
 - CPU's: 3
 - Memory: 16 GB
 - PostgreSQL version: 11.6
 - TimescaleDB version: 1.6.0
 - Installation method: apt

**Describe the bug**

Our simple hypertable (uuid, time, value) contains 7 billion rows divided over 6220 1-week chunks. The size of the chunks varies wildly, but we've made sure that the largest one comprises no more than 25% of main memory. Apart from an index on (time), an extra index (primary key) on (uuid, time) was created to support our queries. The database was tuned via timescaledb-tune. Table statistics were up to date. What we observe is that the query planning time does not scale well with the number of chunks that have to be touched. In contrast, execution time is fast, even for the largest interval (never exceeds 1 second).
```
EXPLAIN ANALYZE
SELECT time_bucket('4week', time) AS bucket, avg(value)
FROM timeseries
WHERE uuid = '12b3a192-d9d8-497a-8dca-d7caf85e25d0'
AND time BETWEEN '2018-01-01' AND '2019-01-01'
GROUP BY bucket ORDER BY bucket;
```

```
'2018-01-01' and '2019-01-01': planning time =     21.745 ms
'2009-01-01' and '2019-01-01': planning time =    470.588 ms
'1999-01-01' and '2019-01-01': planning time =   2024.340 ms
'1989-01-01' and '2019-01-01': planning time =   5188.943 ms
'1979-01-01' and '2019-01-01': planning time =  13587.168 ms
'1969-01-01' and '2019-01-01': planning time =  19318.124 ms
No interval, uuid filter only: planning time = 149704.720 ms
```

**Expected behavior**

We expected less query planning overhead, but are unsure since we're new to timescaledb. Planning times in your blog for 4000+ chunks are much, much smaller: [Optimizing queries on TimescaleDB hypertables with thousands of partitions](https://blog.timescale.com/blog/optimizing-queries-timescaledb-hypertables-with-partitions-postgresql-6366873a995d/).

**Comment by fvannee** [comment]
AFAIK the link you specify consists of mostly queries that target one specific chunk. The total number of partitions may be 4k+, but then the query only is interested in one of them. This kind of query is quite fast, because the optimizations are able to prune away the unnecessary chunks in a very early stage of the planning, before they can cause much overhead.
However, if you're interested in selecting 50 years of data with weekly chunks, the planner will have to build a huge plan with 50*52=2600 chunks. I've noticed before that these kind of queries are quite slow to plan. I'm not sure why the overhead is growing even faster than O(n) though, but it's quite possible nobody in Postgres/Timescale optimized these kind of situations before. Generally I've found that it can get quite painful if you need to run queries that target many chunks in one query.

**Comment by byrman** [comment]
Thanks. I'm currently reducing the number of chunks as much as possible, trying to make them more equal in size. That's a bit of a hassle though, because you don't have precise control over the boundaries and there seem to be no functions for splitting or joining existing chunks. I'll report my findings here.

**Comment by byrman** [comment]
By varying the time interval, I managed to reduce the total number of chunks by a factor 10. This helped a lot. Planning time is still the most important factor (30x higher than execution time), but overall performance is okay now.

**Comment by NunoFilipeSantos** [comment]
There were a lot of performance improvements on TimescaleDB 2.X we strongly advise anyone to upgrade and experiment with the latest and greatest.
