### ISSUE TITLE
function "last(anyelement,"any")" does not exist when accessing continuous aggregate via fdw

### ISSUE THREAD

**Issue by db-adrian** [timescale/timescaledb#1919]
**Relevant system information:**
 - OS: ubuntu:18.04 - docker
 - PostgreSQL version (output of `postgres --version`): 10.12
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: using docker from source
**Describe the bug**
When I want to query a continuous aggregate on a different database via the postgres_fdw I get the error `ERROR: function "last(anyelement,"any")" does not exist`.
I have created a foreign table that points to the continuous aggregate in the remote database.

**To Reproduce**
1. Create a continuous aggregate with a column that uses any timescaledb specific aggregate like last() or first().
2. Create connect from a different database via postgres_fdw to the database which has the continuous aggregate.
3. Create a foreign table that points to the continuous aggregate.
4. Do a query that includes a collum which has a timescaledb specific aggregate.
5. The query fails with `ERROR: function "last(anyelement,"any")" does not exist`

**Expected behavior**
The query should return a result as if it is queried on the database where the continuous aggregate is defined.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Additional context**

**Comment by fncaldas** [comment]
I got this same error here when using pg_promise to call a function from PostgreSQL 12.5 in Ubuntu 20.10:

> error: function last(timestamp with time zone, timestamp with time zone) does not exist

I could solve this error by adding the public schema when calling the last function. However calling my function directly from psql or jbdc interface doesn't trigger the error even when my fuction was in a different schema. It happens only when calling the function from pg_promise.

**Comment by pgwhalen** [comment]
We also got the same error, but from JDBC/JOOq, by switching the schema before reading, e.g.:

```
try (final Connection conn = dataSource.getConnection();
     final DSLContext create = using(conn, SQLDialect.POSTGRES);
     final PreparedStatement schemaSwitch = conn.prepareStatement(create.setSchema(DATA_SCHEMA).getSQL(INLINED));
     final PreparedStatement statement = conn.prepareStatement(dataQuery().getSQL(INLINED))) {
    schemaSwitch.execute();
    ...
}
```

Removing the `schemaSwitch` fixed our problem.

Notably, the issue was not caught in our integration tests that quickly created a continuous aggregate, wrote to the underlying hypertable, and read from the continuous aggregate.  This appears to be because the continuous aggregate was always reading from the underlying hybertable rather than the materialized hypertable.  Sleeping for ten seconds helped us reproduce the issue in a test.

It would be lovely if these `search_path` issues were better handled, or at least the error messages were more obvious (i.e. not having to understand how a timescale-created view is failing to do its job).

-----

`PostgreSQL 12.5 (Ubuntu 12.5-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit`

timescaledb `2.0.1`
