### ISSUE TITLE
[Feature Request] A timescaledb_information.chunks view

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#1950]
Seeing statistics about the chunks underlying a given hypertable would often be useful. Rather than having to go to the pg catalogs to get size information, etc, a view very much like `timescaledb_information.hypertable` would be great - including table, index, and toast sizes for each chunk, as well as their parent hypertable, and other relevant metadata.

**Comment by jflambert** [comment]
I was confronted with a similar problem recently and it turns out timescaledb has quite a few (undocumented?) views or internal tables you can use. Maybe check out [what I came up](https://github.com/timescale/timescaledb/issues/1885#issuecomment-635350946) with the other day and see if it's a starting point for you.

**Comment by erimatnor** [comment]
A chunks view will be in TimescaleDB 2.0, but it will not include, e.g., sizes and indexes. We've decided to make size information available in functions instead and there are already other ways of viewing indexes.
