### ISSUE TITLE
Drop chunks based on time and another value.

### ISSUE THREAD

**Issue by 120bits** [timescale/timescaledb#2044]
Hi,

I have a table which stores data points for a specific device_id and currently the hypertable are partitioned based on time column. So, I'm trying to find a way to drop chunks based of time and device_id. For now I can drop chunks based on this sample query and it works fine, but it drops all the rows for all the IDs. Is there a way I can add an extra condition and drop chunks based on time and id.

`SELECT drop_chunks(INTERVAL '3 months', 'conditions');`

How can I do something like this so it will drop chunks only for that device_id

`SELECT drop_chunks(INTERVAL '3 months', 'conditions', 'device_id);`

Thanks,
Prat

**Comment by k-rus** [comment]
@120bits Thank you for your request. I will clarify that `drop_chunks` drops entire chunks, where a chunk is a partition of a hypertable. Since `drop_chunks` deletes a partition, which is a table under the hood, it is as efficient as dropping a table in PG. In your request you want to drop rows. This can be done by calling [DELETE](https://www.postgresql.org/docs/12/sql-delete.html) and specifying WHERE condition.
I hope it answers your question. I will close the issue. Let me know if you want to reopen it.

**Comment by 120bits** [comment]
@k-rus 
Thanks for the reply. I was wondering if chunks can be partitioned based on time and id. If I DELETE it will be much slower operation than just dropping a chunk.

**Comment by k-rus** [comment]
> Thanks for the reply. I was wondering if chunks can be partitioned based on time and id. If I DELETE it will be much slower operation than just dropping a chunk.

Sorry, it was unclear that you were interested in partitioning by device id. It is possible to partition, however based on the hash function several device id will be stored in one chunk. Partitioning for each device id is possible if it is known in advance, since it is not possible to re-partition existing chunks. Note that many chunks, e.g., if you have 100 device ids, it will be 100 chunks per the same time interval, might affect performance negatively.
It would be interesting to see how you imagine partitioning. A feature request can be open if the complete story is presented.

**Comment by 120bits** [comment]
Hi. @k-rus 

I have a table with device_ids and cpu_usage and time. I have created the hypertable and the chunks are created every 24 hours. It works nice! 

---device_id------cpu_usage-----time
     ID_1                   30.3%             t1  
     ID_2                   35.1%             t2

For my data retention policy I choose the drop the chunks older than 1 month. 
`SELECT drop_chunks(INTERVAL '1 months', 'cpu_usage' );`

It drops all the chunks older than 1 month. However, it drops all the data for ID_1 and ID_2. What if I want to have different retention policies for ID_1 and ID_2. How can I have a additional parameter to the drop_chunk function. 

Dropping chunks seems faster than running a delete query.

`delete from cpu_usage where device_id = ID_1 and time < now() - interval '1 hours'  `

Thanks
