### ISSUE TITLE
Duplicate records inserted even when matches UNIQUE constraints (was: queries don't use index)

### ISSUE THREAD

**Issue by meotimdihia** [timescale/timescaledb#206]
```sql
explain select * from "tables" where timestamp > '2017-09-14 00:57:34+00:00' 
```

```
Append  (cost=0.00..169730.34 rows=6713638 width=61)
--
->  Seq Scan on trades  (cost=0.00..0.00 rows=1 width=266)
Filter: ("timestamp" > '2017-09-14 00:57:34+00'::timestamp with time zone)
->  Seq Scan on _hyper_2_595_chunk  (cost=0.00..161072.44 rows=6364045 width=61)
Filter: ("timestamp" > '2017-09-14 00:57:34+00'::timestamp with time zone)
->  Seq Scan on _hyper_2_596_chunk  (cost=0.00..8657.90 rows=349592 width=61)
Filter: ("timestamp" > '2017-09-14 00:57:34+00'::timestamp with time zone)
```

Same query but with different timestamp: 
------

```sql
explain select * from "tables" where timestamp > '2017-09-15 00:57:34+00:00' 
```

```

QUERY PLAN
--
Append  (cost=0.00..1626.87 rows=35650 width=61)
->  Seq Scan on trades  (cost=0.00..0.00 rows=1 width=266)
Filter: ("timestamp" > '2017-09-15 00:57:34+00'::timestamp with time zone)
->  Index Scan using "2976-trades_timestamp_idx" on _hyper_2_596_chunk  (cost=0.42..1626.87 rows=35649 width=61)
Index Cond: ("timestamp" > '2017-09-15 00:57:34+00'::timestamp with time zone)

```

I don't understand why didn't first query use index.

**Comment by cevian** [comment]
Hi @meotimdihia, The planner is probably not using the index because the statistics tell the planner that almost all the data is after '2017-09-14 00:57:34+00:00' (the planner prefers a seq scan to an index scan when the index scan will not be able to prune a lot of data). Your statistics might be off (which can be fixed by `ANALYZE "tables";`) or the planner might be right. If you do an `EXPLAIN ANALYZE` (vs plain `EXPLAIN`) that will give us more context to debug.

**Comment by meotimdihia** [comment]
my data is indeed almost all the data is after '2017-09-14' . Sorry i am new to postgresql. I am interested in TimesScale : 
And while you are at this problem. Can you help me explain why my query is very slow. It take 20-30 or more to return results in tables just have > 10 millions rows: 


```sql
SELECT time_bucket('5 minutes', timestamp) as five_min, count(*) as count, flag, fsym, tsym 
FROM "trades"
WHERE "timestamp" >= '2017-09-13 13:58:57+07:00' 
      AND ("fsym" = 'BTC' or "tsym" = 'BTC') 
GROUP BY "five_min", "flag", "fsym", "tsym"
ORDER BY "five_min" DESC
```
this is table 
![](https://i.imgur.com/wraDdSw.png)

**Comment by mfreed** [comment]
Can you post the output of "EXPLAIN ANALYZE" for that query?

**Comment by meotimdihia** [comment]
this is output of "EXPLAIN ANALYZE" for my query: 

``` sql

GroupAggregate  (cost=1956918.12..2095951.20 rows=855588 width=26) (actual time=49957.180..54802.305 rows=315294 loops=1)
Group Key: (time_bucket('00:05:00'::interval, trades."timestamp")), trades.flag, trades.fsym, trades.tsy
      ->  Sort  (cost=1956918.12..1978307.83 rows=8555882 width=18) (actual time=49957.169..52666.164 rows=9847166 loops=1)
          Sort Key: (time_bucket('00:05:00'::interval, trades."timestamp")) DESC, trades.flag, trades.fsym, trades.tsym
          Sort Method: external merge  Disk: 271544kB
          ->  Result  (cost=0.00..620842.12 rows=8555882 width=18) (actual time=4.344..21311.461 rows=9847166 loops=1)
              ->  Append  (cost=0.00..513893.59 rows=8555882 width=18) (actual time=4.274..19637.219 rows=9847166 loops=1)
                  ->  Seq Scan on trades  (cost=0.00..0.00 rows=1 width=74) (actual time=0.040..0.040 rows=0 loops=1)
                      Filter: (("timestamp" >= '2017-09-13 06:58:57+00'::timestamp with time zone) AND (((fsym)::text = 'BTC'::text) OR ((tsym)::text = 'BTC'::text)))
                  ->  Seq Scan on _hyper_2_1_chunk  (cost=0.00..64114.17 rows=1161673 width=18) (actual time=4.233..1548.315 rows=1343259 loops=1)
                      Filter: (("timestamp" >= '2017-09-13 06:58:57+00'::timestamp with time zone) AND (((fsym)::text = 'BTC'::text) OR ((tsym)::text = 'BTC'::text)))
Rows Removed by Filter: 810344
                  ->  Seq Scan on _hyper_2_595_chunk  (cost=0.00..196836.85 rows=3310708 width=18) (actual time=0.020..7464.732 rows=3789381 loops=1)
                      Filter: (("timestamp" >= '2017-09-13 06:58:57+00'::timestamp with time zone) AND (((fsym)::text = 'BTC'::text) OR ((tsym)::text = 'BTC'::text)))
Rows Removed by Filter: 2805610
                  ->  Seq Scan on _hyper_2_596_chunk  (cost=0.00..231930.79 rows=3744907 width=18) (actual time=0.024..9313.739 rows=4321102 loops=1)
                      Filter: (("timestamp" >= '2017-09-13 06:58:57+00'::timestamp with time zone) AND (((fsym)::text = 'BTC'::text) OR ((tsym)::text = 'BTC'::text)))
Rows Removed by Filter: 3470872
                  ->  Seq Scan on _hyper_2_597_chunk  (cost=0.00..21011.78 rows=338593 width=18) (actual time=0.748..374.142 rows=393424 loops=1)
                      Filter: (("timestamp" >= '2017-09-13 06:58:57+00'::timestamp with time zone) AND (((fsym)::text = 'BTC'::text) OR ((tsym)::text = 'BTC'::text)))
                      Rows Removed by Filter: 312665

Planning time: 1993.388 ms
Execution time: 54856.577 ms
```

**Comment by mfreed** [comment]
Hi @meotimdihia:   So the GROUP BY / ORDER BY is causing it to need to compute a SORT, and it looks like the 10M rows take up 271MB.  The reason it's slow is because it's actually doing this merge on disk, rather than in memory:
```
  Sort  ...  (... rows=9847166 loops=1)
      Sort Method: external merge  Disk: 271544kB
```
If you want a big performance boost, you'll need to increase your `work_mem` so this sort can stay in memory.  

Now the risk is that this is what is used by each of your connections, so the total consumption is `work_mem * max_connections`.   But if you know something about your use case (like a small number of concurrent queries), and a fairly well-provisioned server, you can set `work_mem` quite a bit higher.  

For more on this:   https://www.postgresql.org/docs/9.6/static/runtime-config-resource.html

**Comment by meotimdihia** [comment]
I fixed work_mem and its work . The line: "external merge Disk ..." don't appear.

Thanks for your helps. I still have 2 questions:  
### - "Explain Analyze" does not notify when there is not enough memory 

this is output of instance shared CPU and 1.7GB  (execution time 6s)
https://i.imgur.com/akXuywH.png
this is output of instance 1 CPU and 7 GB: (execution time 130s)
https://i.imgur.com/RKi12Mf.png

output is the same , with different numbers.  

Its just my guess, the first instance is lack of memory. And chunk_tables have total_size is ~ 1500MB.
Its good if we have details about how much memory we need when analyze query.

### - Unique Indexes doesn't seems to work for me  


This is tip in Timescale documention : 
> TIP: To a define an index as UNIQUE or PRIMARY KEY, the time column and, if it exists, the partitioning column ​must​ be the first (or first two) columns that comprise the index. That is, using our running example, you can define a unique index on just the {time, location} fields, or to include a third column (say, temperature), the index must be specified as {time, location, temperature}. That said, we find UNIQUE indexes in time-series data to be much less prevalent than in traditional relational data models.

this is my table, after altered 

![](https://i.imgur.com/CPLMosV.png)

But i still can insert duplicate multiple rows.

**Comment by mfreed** [comment]
```Its good if we have details about how much memory we need when analyze query.```

I'm not sure I understand your question.  Looking at that query should give you an idea how much memory is required.  I'm not fully certainly how to interpret your first comment offhand, though, as to what the difference between those two machines are.

As aside, it might be more productive to offer this general type of help over Slack rather than github:  http://slack-login.timescale.com/

Regarding the UNIQUE, you can insert two values with identical (timestamp, exchange, id, fsym, tsym)?  Can you provide the specific INSERTed values and show that they appear twice when you do a SELECT?

**Comment by meotimdihia** [comment]
This is my insert query: 
```sql
INSERT INTO "trades" ("exchange", "id", "fsym", "tsym", "timestamp", "quality", "price", "total", "flag", "api") VALUES
('BITF',	'65907655',	'BTC',	'USD',	'2017-09-14 10:35:56+07',	'0.01486857',	'3822.7',	'56.83808254',	2,	'coinigy');
```
![](https://i.imgur.com/SIhyxzp.png)
Find above record: 
```sql


SELECT * FROM trades
WHERE timestamp  = '2017-09-18 01:12:59+00' AND exchange = 'BITF'	AND id = '67962374' AND fsym = 'ETH' AND tsym = 'BTC'
```

![](https://i.imgur.com/futDBTT.png)

We have two identical rows now.

**Comment by mfreed** [comment]
Notes from addition discussion on Slack:

- Only partitioning is by time (timestamp)
- Running version 0.4.2

**Comment by mfreed** [comment]
This issue should be addressed by PR https://github.com/timescale/timescaledb/pull/198, which will appear shortly in release version 0.5.

**Comment by RobAtticus** [comment]
Hey, it appears this is a problem with how we were having `ALTER TABLE...ADD UNIQUE CONSTRAINT` commands where the change was not being propagated to the chunks. As @mfreed noted, this has been fixed in the upcoming 0.5.0 release.

One caveat: If you are trying to upgrade to 0.5.0 with a table that has duplicates in violation of the unique constraint, the process will fail and you will be stuck in a weird limbo state. There are two ways to handle the upgrade:

1. If it is easy enough, you can just start fresh with 0.5.0.
2. If not, you will need to remove the duplicate records BEFORE upgrading to avoid any hiccups.

**Comment by mfreed** [comment]
Fixed in https://github.com/timescale/timescaledb/releases/tag/0.5.0 release. See PR #198.

**Comment by meotimdihia** [comment]
i updated successfully and fixed this problem too.
