### ISSUE TITLE
Support Compression on Continuous Aggregates

### ISSUE THREAD

**Issue by nwut** [timescale/timescaledb#2072]
I found my continuous aggregates size is huge. 
and it's not easy to find size of continuous aggregates.

How possible to add chunk compression feature for continuous aggregates?

**Comment by jkern888** [comment]
I'm also finding my continuous aggregates are larger than I expected them to be. It be really nice to also have compression available on the chunks, but in the meantime I'm wondering if there is any advice on how to minimize the disk space used by the aggregate?

**Comment by mkindahl** [comment]
Adding compression to continuous aggregates means that we add compression to the internal materialized hypertable. In effect, this means that we would support calling `compress_chunk` on chunks in the materialized hypertable and, more importantly, compression policies for continuous aggregates.

This has a few consequences:
- Since compressed chunks are not writable, this effectively freezes that range of chunks and they cannot be updated. This means that any continuous aggregate policies that update ranges that are compressed will fail when executed either with an error or with a warning.
- We can only compress full chunks, so this cannot be used to freeze an arbitrary range of the continuous aggregate.
- Since this will be used as a feature to freeze a range of chunks, we would have to add checks that a compressed range is not updated. This since a future support for updating compressed chunks might change this behavior, and we do not want to accidentally trigger an update where one is not desired (because the range is compressed but it is suddenly possible to update compressed chunks).

**Comment by marioishikawa** [comment]
This would be incredible.

**Comment by pbysh** [comment]
This would be a game changer for our team, strong +1

**Comment by erimatnor** [comment]
@mkindahl IMO, users shouldn't have to manually compress continuous aggregates (e.g., via `compress_chunk`), it should be transparent.

The data in a continuous aggregate need not support inserts, and it is only updated at an explicit `refresh_continuous_aggregate`, which means we could compress when we refresh. It would be odd to have to call `compress_chunk` after `refresh_continuous_aggregate`, especially if the continuous aggregate was compressed and the refresh then makes the data uncompressed again.

Note that the current materialization process basically does first a `DELETE` then an `INSERT` on the range refreshed. So, the old data is thrown away anyway. We could just compress when we insert the new data.

Also, I am not 100% convinced that `compress_chunk` is the right approach. Maybe it is just easier to run the partial aggregate through compression in the serialization and deserialization functions:

* `_timescaledb_internal.partialize_agg` would compress the partial
* `_timescaledb_internal.finalize_agg` would decompress the partial

This would be a transparent change.

**Comment by ogrok** [comment]
Wanted to leave a +1 here as well, as this would be highly beneficial to my team

**Comment by raschan** [comment]
This would be really useful for our team too.

**Comment by pbysh** [comment]
For those interested, we have rolled our own compression of continuous aggregates by creating a separate hypertable for the compressed data in addition to our original, uncompressed continuous aggregate, then running a job using the job scheduler that grabs the last chunk of the cagg and moves it over to the hypertable and compresses it. Then we created a view that unions the two tables and for all intents and purposes it works as a single compressed continuous aggregate.

**Comment by mpatelj** [comment]
+1

**Comment by tatjana-repa** [comment]
> For those interested, we have rolled our own compression of continuous aggregates by creating a separate hypertable for the compressed data in addition to our original, uncompressed continuous aggregate, then running a job using the job scheduler that grabs the last chunk of the cagg and moves it over to the hypertable and compresses it. Then we created a view that unions the two tables and for all intents and purposes it works as a single compressed continuous aggregate.

Thanks for the idea. The size of our cagg table is 4 TB and it's been growing. Data compression is what we need. We are trying to implement the same thing as above. How do you do the data moving from cagg  chunk to hypertable though? I though I will be able to move the chunk itself, but DDL of cagg is not the same as a hypertable. For now I just do "select * from materialized_view_of_cagg where ts >= ''range_start_timestamp" and ts < "range_end_timestamp", but it takes long. My chunk size is 10 GB only in simulation environment, but in production will be 20 times more. I am just afraid we'll run out of memory or it will take a ridiculous amount of time to move data. May be there's an easier way?

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 Compression on Continuous Aggregates was merged and is about to drop in our TimescaleDB 2.6 release. 
https://github.com/timescale/timescaledb/pull/3873
