### ISSUE TITLE
Continuous aggregate materializer uses unbounded memory

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2130]
The continuous aggregate materializer suffers from poor use of memory contexts to prevent excessive memory usage. In particular, it scans for invalidations (which can be an unbounded scan) an accumulates them in a list. Then this list is used in another double-loop scan over a list of all continuous aggregates for a hypertable to copy invalidations; once per cagg. Again, this scan isn't using  best practices for managing such unbounded scans of many items, such as a per-tuple memory context.

The materializer code needs a major overhaul to fix these issues, e.g., by judiciously applying the use of per-tuple memory contexts. 

Related to #2074.

**Comment by erimatnor** [comment]
The intention is that this will be addressed as part of the continuous aggregate refactoring.

**Comment by zivyankelevitz** [comment]
Hello erimatnor,

we recently started using timescale/timescaledb:1.7.2-pg10 (before that we used 1.0.0 version)
this was done in order to start using the mealtime continues aggregation feature.
we created several views (hourly and daily aggregations over the existing raw data hyper tables:
e.g.    CREATE VIEW gnss_port_status_daily   WITH (timescaledb.continuous) AS ...

we have noticed a very large memory usage which is continuously growing until container memory usage saturation is reached (~5GB Ram). 
before using this feature, with same DB, and same amount of data and insertion rate for the raw data tables(~160 rows per second) we noticed timescale consumed about 2.5GB Ram

is this behavior can be related with your findings here?
do you think it is a matter of bad configuration for the timescale/views ?

thanks,
Ziv

**Comment by erimatnor** [comment]
@zivyankelevitz Thanks for trying TimescaleDB. We just released version 1.7.3, which includes fixes for this issue. Please try that version and see if it solves your problem. We will close this issue in that case.

**Comment by zivyankelevitz** [comment]
thank you very much. we will try it :-)

**Comment by erimatnor** [comment]
Closing this due to fixes in 1.7.3. Version 2.0 will also see a major overhaul of the materializer, which should reduce memory usage. Issue can be reopened if issues persist.

**Comment by zivyankelevitz** [comment]
ok. for now it does use a lot of memory. looking forward to here from you when the major overhaul is over. thanks

**Comment by Splitframe** [comment]
I run into the same issue, our host system has 64GB RAM. For the postgres settings I used TuneDB.
The hypertable is rather large, around 1TB for 3 years of data. Even if I only refresh the aggregate for a single month
it takes more and more memory until it reaches ~50GB and the OOM Reaper comes.
