### ISSUE TITLE
Test/improve UX of continuous aggregate refresh in combination with retention policy

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2198]
Retention via `drop_chunks` on a hypertable that has continuous aggregates can interact in unexpected ways  with refreshes. For instance, if you drop data in a region and then refresh a continuous aggregate in the same region, then the aggregate will lose data. See https://github.com/timescale/timescaledb/issues/2198#issuecomment-690941152 for the description of this corner case.

We should have tests that explore these cases and, ideally, allows preventing accidental deletions of aggregate data via privileges on the continuous aggregate.

Related to #2135

**Comment by k-rus** [comment]
There is an interesting corner case, which might provide unacceptable UX. One user scenario, which we think is common, is when a retention policy is created on a hypertable, which also has continuous aggregates, and while only recent data is retained in the hypertable, the user want to retain all data in the continuous aggregates. A natural way to achieve this is to defined start of the refresh window at the same interval as the retention window. For example, the retention window is one month, then the start of the refresh window is one month too.

However, there is a corner case when some data will not retain in the continuous aggregate after data are dropped by the retention policy. To understand this corner case I will explain current implementations. The retention policy drops chunks, which are strictly older than the retention window. The refresh continuous aggregate policy refreshes all buckets, which fully covers the refresh window, i.e., the refresh might update larger window than specified in the refresh policy. This is due to buckets, chunks, retention windows and refresh windows are not aligned and cannot be aligned with each other.

I will illustrate this corner case with pictures.

The following picture illustrates that the corner case happened at some moment in time:
![Cagg and retention corner case, initial](https://user-images.githubusercontent.com/1726044/92886557-08a86b80-f414-11ea-946e-ec38e6774d0f.png)

Then the retention policy was successfully run, which resulted in this picture:
![Cagg_retention_dropped](https://user-images.githubusercontent.com/1726044/92887989-37731180-f415-11ea-85d4-3a082ce723e4.png)
Then immediately the refresh continuous aggregate policy run and due to overlaps between the policies some data are deleted from the continuous aggregate due to deletion from the refreshed bucket:
![Cagg_retention_run_refreshed](https://user-images.githubusercontent.com/1726044/92888356-85881500-f415-11ea-81f9-85537b752b37.png)
This deleted data is a bug in the current implementation, imho.

**Comment by erimatnor** [comment]
@k-rus first, thank you for the exemplary information. FWIW, I don't think this is specific to policies or drop_chunks. You can do, e.g., `DELETE FROM foo WHERE time < X`, which would create a "drop-off" point which is not necessarily aligned with chunk boundaries but otherwise poses the same issue for refreshing.

So, how do we distinguish between that case and the drop_chunks case? I don't see a distinction between them really, since they are just two ways of deleting data with similar results. How do we deal with partial deletes, e.g., `DELETE FROM foo WHERE time < X and device=1`? Would that data deletion also fall under the "should-not-refresh" distinction?

Do you have a proposed solution? Should we instead align the refresh window to the closest buckets that are completely enclosed by the refresh window, i.e., refresh less than asked for? I am actually not sure that solves the general problem.

I think the only valid solution would be to provide a "freeze" functionality where buckets in the cagg are frozen, and thus protecting them from further refresh. This side-steps all the alignment issues.

**Comment by k-rus** [comment]
> FWIW, I don't think this is specific to policies or drop_chunks. You can do, e.g., `DELETE FROM foo WHERE time < X`, which would create a "drop-off" point which is not necessarily aligned with chunk boundaries but otherwise poses the same issue for refreshing.

Good point! I agree the user will run into the same unexpected experience without using policies. So the solution will need to work in all combinations, where on one side it can be retention policy, `drop_chunks` or `DELETE`, and on another side refresh policy or manual refresh.



> Do you have a proposed solution?

No. My first concern is to explain the issue and convince that this needs to be fixed. So far, nobody explicitly agreed that it is an issue to resolve.



> Should we instead align the refresh window to the closest buckets that are completely enclosed by the refresh window, i.e., refresh less than asked for? I am actually not sure that solves the general problem.

I think this solution should fix this bug in all cases. You mentioned that it is rather simple change. So I suggest to do it if we don't get a better idea or until we don't have a better solution :) imho, this issue should be treated as a bug and fixed before 2.0.0 release.



> I think the only valid solution would be to provide a "freeze" functionality where buckets in the cagg are frozen, and thus protecting them from further refresh.

This solution will not help if freeze wasn't called, which will not happen in the case of `DELETE`. So I feel it will reduce how often the corner case happens, but will not eliminate the bug completely.

**Comment by erimatnor** [comment]
@k-rus I don't think it is a bug, but not sure that the designation matters either; I agree that we should solve it in either case since it is certainly a UI/UX issue. If people understand that refreshes are bucket aligned to next largest bucket (which would be documented), they could compensate, but I agree it is easy to miss this corner case.

So, this is about the semantics of refresh: should we refresh all the buckets in the window that people requested to be refreshed, or should we not refresh buckets that fell within the window. As long as the semantics are clear, I think we can do any of these. I initially figured it is best to refresh at least the amount requested. You raised this corner-case as an argument in favor of reducing the refresh to closest fully enclosed buckets and I think it is a good argument in favor of this. So, do you want to create an issue that we should shrink the refresh window rather than expanding?

**Comment by k-rus** [comment]
> So, do you want to create an issue that we should shrink the refresh window rather than expanding?

@erimatnor Can we use this issue instead of adding another one?

**Comment by erimatnor** [comment]
> > So, do you want to create an issue that we should shrink the refresh window rather than expanding?
> 
> @erimatnor Can we use this issue instead of adding another one?

I guess. Btw, how do we deal with refresh windows that are smaller than one bucket. With the proposal, such refreshes will do nothing, i.e., they won't refresh anything. I guess we should raise an error that the window must be at least one bucket in size?

**Comment by k-rus** [comment]
> I guess we should raise an error that the window must be at least one bucket in size?

@erimatnor I support this idea to return error if the refresh window is too small.
