### ISSUE TITLE
Trying understand data retention concept

### ISSUE THREAD

**Issue by cassioeskelsen** [timescale/timescaledb#242]
I work with data series a few years ago but always in common relational DBs, I'm new to the world of TSDB and I'm not understanding some concepts.
The data you work with (weather stations) need to be stored as-is for years to allow historical series queries.
What would be the best way to model this in a Timescale database? Just leave the data in the hypertable (do not execute the drop chunck) or create a separate table for raw data?
In both cases I would have no benefit of using a TSDB, correct? This is one of the biggest problems I face today, that of having minimal speed in searching for this data and without crashing the whole server.

**Comment by mfreed** [comment]
Hi @cassioeskelsen I'm not sure I understand the question, but you can indeed store the raw data indefinitely (provided you have sufficient storage).  You can also have *multiple* hypertables, so it's not uncommon to keep raw data in one table and aggregated data in another table.  Sometime that's so you don't keep raw data indefinitely, but it can also be for performance if you know many queries are interested in these aggregates (i.e., compute them once rather than always at query time).

Regarding "no benefit" of TimescaleDB vs. vanilla Postgres or another relational data:  That's certainly not true.  Even with your raw data, TimescaleDB will give much higher insert throughput,  more performant queries, and a set of time-oriented analytical/management functions.

For more information on this:
  - Postgres vs. TimescaleDB comparisons:  https://blog.timescale.com/timescaledb-vs-6a696248104e
  - Technical explanation of *why*: https://blog.timescale.com/time-series-data-why-and-how-to-use-a-relational-database-instead-of-nosql-d0cd6975e87c

**Comment by cassioeskelsen** [comment]
Hi @mfreed !

Yes, you understood, that's what I needed to know. (I'm sorry, English isn't my first language, I may not be expressing myself correctly)

My question was basically about "best practices" in a scenario where data should be kept indefinitely. I will then keep everything in a single hypertable: data that needs to be queried in realtime (with the appropriate chunk size for my situation) without ever deleting(drop_chunks) them to allow for querying older data.

Thanks for the answer!
