### ISSUE TITLE
timescaleDB: drop_chunks fails for hypertable with cagg, the continuous aggregate is too far behind

### ISSUE THREAD

**Issue by poojabms** [timescale/timescaledb#2570]
Hello experts,

We are using TSDB for our product and things are going good except for the retention policy that is giving us tough time.
Here is my requirement:
1. main_table will be receiving data as generated, and will retain this data for 24 hours. After 24 hours the data should be deleted.
2. daily_aggregates is the continuous aggregate created on main_table which will be aggregating daily data. After 6 months, the data from this view should get deleted.

Here are my queries:
(Eventually I will be using select add_drop_chunks_policy command, but only when drop_chunks issue is fixed.)

CREATE TABLE IF NOT EXISTS main_table ( id BIGSERIAL NOT NULL,created TIMESTAMP, name TEXT, PRIMARY KEY (id, created)); 

SELECT create_hypertable('main_table', 'created', chunk_time_interval => INTERVAL '24 hours');

CREATE view daily_aggregates with(
timescaledb.continuous, 
timescaledb.ignore_invalidation_older_than = '23 hours'
)
 AS SELECT 
time_bucket('24 hours', created) AS day, 
name, 
min(created) AS created, 
min(id) AS id 
FROM main_table 
GROUP BY day, name;
		
SELECT drop_chunks(INTERVAL '6 months', 'daily_aggregates');
SELECT drop_chunks(INTERVAL '24 hours', 'main_table', cascade_to_materializations=>false);

Since my older_than is set to 24 hours, I have set the ignore_invalidation to 23 hours. However, this just doesn't work and throws:
2020-10-19 13:05:19.269 CEST postgres postgres [20043]**_ERROR:  the continuous aggregate public.daily_aggregates is too far behind_**
2020-10-19 13:05:19.269 CEST postgres postgres [20043]STATEMENT:  SELECT drop_chunks(INTERVAL '24 hours', 'main_table', cascade_to_materializations=>false);

The doc mentions, **'''TIP:By default, calling drop_chunks on a table that has a continuous aggregate will throw an error. This can be resolved by setting cascade_to_materializations to TRUE, which will cause the corresponding aggregated data to also be dropped. '''**

But this isn't what I want. I don't want the data from the cagg to be deleted when the data from main table is dropped off. I want to retain the aggregate for 6 months, and main_table's data only for 24 hours.

What am I missing? Any help is greatly appreciated. If I can't fix this in another 2 days, we will have to let go off TSDB.

**Comment by gayyappan** [comment]
@poojabms  Questions related to usage are better addressed via our support slack. 
When you try to drop the data from the hypertable, the data has not yet been aggregated into the continuous aggregate and so the drop fails. You can delay dropping the chunks from the hypertable (i.e. keep data for a longer time, e.g. 48 or 96  hours worth of data instead of 24 hours). This would let the continuous aggregate job process the data before you delete it.  
Some things to note:
1. The continuous aggregate processes only full buckets. So if you have partial data for today, say starting from 12 am to 12 noon, the data is not processed by the continuous agg until it has 24 hours of data for that time_bucket. 
2. You will find details related to the next time the job will run, the data point that was processed etc in  **timescaledb_information.continuous_aggregate_stats**.
3. refresh_lag plays a part in determining the data that gets materialized by the continuous aggregate. (Refer to https://docs.timescale.com/latest/tutorials/continuous-aggs-tutorial)
