### ISSUE TITLE
Can't install TimescaleDB to PostgrsPro12

### ISSUE THREAD

**Issue by emacsway** [timescale/timescaledb#2642]
**Relevant system information:**
 - OS: CentOS Linux release 7.8.2003 (Core)
 - PostgreSQL version (output of `postgres --version`): PostgrsPro12
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4
 - Installation method: "source"

**Describe the bug**
```
[ 33%] Building C object src/CMakeFiles/timescaledb.dir/plan_agg_bookend.c.o
/timescaledb/src/plan_agg_bookend.c: In function ‘mutate_aggref_node’:
/timescaledb/src/plan_agg_bookend.c:120:9: error: too few arguments to function ‘expression_tree_mutator’
  return expression_tree_mutator(node, mutate_aggref_node, (void *) context);
         ^
In file included from /timescaledb/src/plan_agg_bookend.c:44:0:
/opt/pgpro/std-12/include/server/nodes/nodeFuncs.h:132:14: note: declared here
 extern Node *expression_tree_mutator(Node *node, Node *(*mutator) (),
              ^
/timescaledb/src/plan_agg_bookend.c:121:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [src/CMakeFiles/timescaledb.dir/plan_agg_bookend.c.o] Error 1
make[1]: *** [src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [all] Error 2
```

**Expected behavior**
Built

**Actual behavior**
Error of compilation

**Comment by franchb** [comment]
I had the same issue a few weeks ago. Guys from [Postgres Professional](https://github.com/postgrespro) told that most likely there could be difficulties with installing TimescaleDB on PostgresPro, especially for the Enterprise version. So we switched to plain Postgres.

**Comment by mfreed** [comment]
We spoke with PostgresPro folks a few months ago, and I believe the issue is that the PostgresPro distributio includes API modifications to "vanilla" Postgres (a la from the PostgreSQL Global Development Group), such that TimescaleDB does not compile against the PostgresPro distribution.

I believe you came across some of these issues above; I don't think this has anything to do with "Enterprise" (which is removed in TimescaleDB 2.0 completely, and the above files referenced are OSS regardless).   Sorry!
