### ISSUE TITLE
Why is a table with one chunk stored for 2 days?

### ISSUE THREAD

**Issue by Barolina** [timescale/timescaledb#2649]
I use timeseriesdb 1.7.4. 
I created a hypertable chunk 1 day. 

Example  my timestamp: 2020-04-04 03:00:00.

Why is a table with one chunk stored in 2 days?

**Comment by Barolina** [comment]
And  my  explain 

![изображение](https://user-images.githubusercontent.com/5443003/99246933-2da3cb00-2817-11eb-91d1-fa7baa26f9db.png)

**Comment by mfreed** [comment]
Hi @Barolina I'm not sure I understand the question, my apologies.  Can you try to explain it a bit further what you are asking?

**Comment by Barolina** [comment]
I have a data

```
  id   time                                 total
  1	2020-04-01 01:00:00	1
2	2020-04-01 01:00:00	1
3	2020-04-01 01:00:00	1
4	2020-04-01 01:00:00	1
5	2020-04-01 01:00:00	2
6	2020-04-01 01:00:00	1
7	2020-05-01 01:00:00	1
8	2020-05-01 01:00:00	1
9	2020-05-01 01:00:00	1
10	2020-05-01 01:00:00	1
.....
```
I  create a hypertable:

```
 SELECT create_hypertable('my_data','time',chunk_time_interval => interval '1 day');
```

Then i see  chanks

```
* 1 chunk *

only 
2020-04-01 01:00:00	1
2020-04-01 01:00:00	1
2020-04-01 01:00:00	1
2020-04-01 01:00:00	1
2020-04-01 01:00:00	2
2020-04-01 01:00:00	1

*2 chunk*

mixed 2020-04-01 01:00:00 and 2020-05-01 01:00:00

*3 chunk*

only 2020-05-01 01:00:00

```
But every chynk have  1,3 G size.

I think,  if i create  interval '1 day' i get  one chunk with  one date.?

My question: Why do  chunk a number 2  have a  mixed data?

Thanks)

**Comment by Barolina** [comment]
> 
> 
> Hi @Barolina I'm not sure I understand the question, my apologies. Can you try to explain it a bit further what you are asking?

**Comment by Barolina** [comment]
Thanks)

**Comment by mfreed** [comment]
@Barolina It shouldn't.  Are you sure those are the actual timestamps, rather than time bucketed (as they are all showing at exactly the same time)?  Note that your chunk boundaries are often not aligned exactly to the day, but can be an arbitrary region of 24 hours.  So it would then be natural that some data from one day falls in one chunk while other data _from the same day but a different time_ falls in another chunk.

Your above shows data actually a month apart, but also data from the same time falling in two different chunks, which shouldn't happen.  My guess it's just a made-up example you are trying to show, but probably doesn't actually hold if you look at the data itself.

If you could print the output of:

```
SELECT chunk_table, partitioning_columns, ranges, total_size
   FROM chunk_relation_size_pretty('my_data');
```

**Comment by Barolina** [comment]
This is 

```SELECT chunk_table, partitioning_columns, ranges, total_size
   FROM chunk_relation_size_pretty('my_data');```

![изображение](https://user-images.githubusercontent.com/5443003/100328389-84f72780-2fdd-11eb-94ba-0f2443c00ff4.png)

But,   if  show  a  chunk1_1
![изображение](https://user-images.githubusercontent.com/5443003/100328650-d0113a80-2fdd-11eb-99e1-f0ab7b5baf89.png)

And  chunk 1_2

![изображение](https://user-images.githubusercontent.com/5443003/100328798-fafb8e80-2fdd-11eb-8748-d4a696df01e8.png)
