### ISSUE TITLE
Why  do Timescale use to index scan for only a one chunk  and other chunks only  a scan index?

### ISSUE THREAD

**Issue by Barolina** [timescale/timescaledb#2652]
Please,  i don't understand
Why  dont timescale use to a index  scan?

Timescale use to index scan for only a one chunk  and other chunks only  a scan index

![изображение](https://user-images.githubusercontent.com/5443003/99277986-90a95800-283f-11eb-867a-24fa23744ed2.png)

**Comment by mfreed** [comment]
Hi @Barolina:  There could be a variety of reasons that the planner made this decision, the most likely that your statistics on each chunk perhaps are not up-to-date (or due to the selectivity of your filter as it applies to that specific chunk).

One thing to make sure is that you have autovacuum; you can try manually analyzing the hypertable and seeing what happens afterwards.

**Comment by Barolina** [comment]
I did  select join  from  then  chunk and  as  well only **Scan Insex**

![изображение](https://user-images.githubusercontent.com/5443003/100499288-5d3cc680-3179-11eb-926e-8e467a917404.png)

**Comment by mfreed** [comment]
I'm still not following.

Can you please post your (a) schema including indexes (preferable `\d+ <hypertable>`), (b) the query, and (c) the full EXPLAIN ANALYZE.  Please be sure to run "VACUUM ANALYZE" on the hypertable before running the explain analyze.

**Comment by NunoFilipeSantos** [comment]
Closing this issue. 
@Barolina if you can add more information, feel free to reopen it.
