### ISSUE TITLE
Single-node to multi-node migration

### ISSUE THREAD

**Issue by dennisjac** [timescale/timescaledb#2701]
What strategies are there to migrate a single-node TimescaleDB setup to a multi-node one with minimal downtime? As far as I can see the only way to do this right now would be to dump the database and import it again into a multi-node instance but for any non-trivial database size this will incur a prohibitively long downtime especially as the nature of the data (timeseries tend to contain lots of rows) make logical dumps/restores extra expensive.
What would be alternative strategies here that would keep the downtime at a minimum?

**Comment by erimatnor** [comment]
Currently, the only way to migrate is to do a `INSERT INTO newtable .... SELECT * FROM oldtable;`. That said, we have plans for more seamless migration where one can incorporate an existing single node instance into a multinode setup by making it a data node and sticking an access node in front of it. That would create a multinode setup with one data nod, which obviously isn't ideal, but it would make the migration almost seamless and it would be possible to add additional nodes from there on.

This migration feature is still in design stage, and there are no guarantees that it will happen at this point. But this also depends on demand and balancing against other priorities.

**Comment by binakot** [comment]
Hello! 
I really interested in migration from Timescale 1.x to 2.x after official release and first patches :) 
Atm I have single node setup of Timescale 1.7: single master + 2 async streaming replicas. The size is about 4 TB.
It would be great if Timescale team write a guide or even migration tool for that! Because I don't see any way to migrate except INSERT new SELECT old.

**Comment by svenklemm** [comment]
multinode has been removed
