### ISSUE TITLE
IS NULL on hypertable timestamp field doesn't work

### ISSUE THREAD

**Issue by sscots** [timescale/timescaledb#2717]
OS: RHEL 7.6
PostgreSQL version: 11.8
TimescaleDB version: 1.7.1
Installation method: unknown

I have a hyper table with a column of type "timestamp without timezone" that allows for NULLs. However I've come across a single instance where a row had a NULL value for that column (An actual NULL, not a string representation or anything else) and the row wasn't being returned when filtering on that column using "IS NULL"

If I run this query below, I get 0 results
`
SELECT late_time, pg_typeof(late_time), CASE WHEN (late_time IS NULL) THEN 1 ELSE 2 END FROM lic WHERE serverid = 7 AND hand = 12345 AND late_time IS NULL;
`

If I remove the "late_time IS NULL", then I get the following 1 result
`
SELECT late_time, pg_typeof(late_time), CASE WHEN (late_time IS NULL) THEN 1 ELSE 2 END FROM lic WHERE serverid = 7 AND hand = 12345;
`
~~~~
  late_time |          pg_typeof          | case
  -------------+-----------------------------+------
            | timestamp without time zone |    1
~~~~

Then if I run the following query with an alternative way to filter by NULL, I do get the same 1 result
`
SELECT late_time, pg_typeof(late_time), CASE WHEN (late_time IS NULL) THEN 1 ELSE 2 END FROM lic WHERE serverid = 7 AND hand = 12345 AND CASE WHEN late_time IS NULL THEN true ELSE false END;
`
~~~~
  late_time |          pg_typeof          | case
  -------------+-----------------------------+------
            | timestamp without time zone |    1
~~~~

So it appears that it's happening when specifically using "IS NULL" in the WHERE clause on the field and just for this specific row instance. It will return valid results on other row instances that have NULL as its value. There are probably less than 10 row instances this is happening for out of about 100k rows with that column set to NULL.
Also, this field was inserted with a NULL value and then later updated with a NULL value again, if that matters.

**Comment by svenklemm** [comment]
Can you post your table definition including the create_hypertable call. Can you reproduce the issue on a new hypertable?

**Comment by sscots** [comment]
I can't reproduce the issue because it's so random and it only happens in less than 1 out of 1k records. 
However, I think I have solved the issue by dropping an index on that column and recreating the index with late_time IS NULL specified.
I had initially created a brin index with that late_time column when it was NOT NULL. Then I modified the column to accept NULL values and that's when I started seeing the issue trying to find records that were NULL. 
Since dropping the index and recreating it, I haven't seen the issue.

**Comment by NunoFilipeSantos** [comment]
Closing since we are unable to reproduce it.
Feel free to reopen it.

**Comment by theblinkingusb** [comment]
Hello team, posting here because I ran into this today, pg17.5, ts 2.20.1. This problem has persisted for a few weeks but had time today to dig in.

The where clauses in question were "runUtc" is null and "completedUtc" is null, where in this situation both columns are full nulls. I have a filtered index on those columns (avail below), if I ran with one or the other clauses, or did an artificial coalesce (causing the engine to do a table/seq scan), the result set would return. If I ran with both (where explain analyze would show index scan), no result set would return.

Records are being inserted daily across multiple "feed"s and "pathKey"s. All records are inserted into this table with null "runUtc" and "completedUtc", and updated after. No other feed/pathKey combo had this issue (across a few hundred combinations).

Rebuilding the index has caused the original query to work as expected ("runUtc" is null and "completedUtc" is null;). I will report back if future inserts still have an issue after the rebuild of the index. For brevity, I have reduced the number of columns, there are a few more jsonb columns and timestamptz columns.

CREATE TABLE words.tasks (
	"insertUtc" timestamptz NOT NULL,
	"runUtc" timestamptz NULL, 
	"completedUtc" timestamptz NULL,
	feed varchar(255) NOT NULL,
	"lastKnownState" varchar(255) NOT NULL,
	"pathKey" varchar(255) NOT NULL,
	core jsonb NOT NULL DEFAULT '{}'::jsonb,
	"streamOps" jsonb NULL,
	"jobRank" int4 NOT NULL
);
select * from create_hypertable('words.tasks', 'insertUtc', chunk_time_interval => interval '7 day', if_not_exists => true);

CREATE INDEX ix_tasks_boost ON words.tasks USING btree ("runUtc", "completedUtc", feed, "lastKnownState", "jobRank" DESC, "insertUtc") WHERE (("runUtc" IS NULL) AND ("completedUtc" IS NULL)); -- where clause to return records heavily uses this.

CREATE INDEX "tasks_insertUtc_idx" ON words.tasks USING btree ("insertUtc" DESC);

Background - 
This table has been side by side upgraded since pg 15. This table had a table corruption error in pg16 but was rebuilt via dirty pages full vacuum (it's an event table so was okay for minor data loss, about 10 records). In my mind, the db corruption is not relevant here because the side by side 16->17 upgrade would have rebuilt the table, but I am not 100% sure on that. This table currently has 1.4m records, but has had 10m+ records in it at times. This same table definition is also replicated for different applications and works fine, it was just this one table, on this one feed/pathKey combination having this issue.

It does seem like a very specific/nuanced issue, not sure that this issue needs to be reopened, but did want to post for others if it helps in the future.

Anyways, thanks tiger/timescale team! Appreciate y'all. 

Edit - the behavior returned - vacuum full "fixed" it. I was able to reproduce the exact issue on my table prior to vacuum full. My query is self referencing (it pulls the most recent record in a cte (by chunk/hypertable key) and then updates the base table via exact match on insertUtc value) and the query would not show for that feed/pathKeyof records, despite having records on one side of the self-reference.  Based on after action research I believe I had some visibility map corruption - or outdated indexes. I only rebuilt the ix_tasks_boost above and not the tasks_insertUtc_idx index yesterday. I have a greater understanding of visibility map corruption diagnosis now, and since this table accordions a lot, possibly I will be able to track this further in the future. Just leaving this note in case it helps the community in the future. Thanks.
