### ISSUE TITLE
Data retention policy based in number of rows

### ISSUE THREAD

**Issue by jfcalvo** [timescale/timescaledb#285]
I can only see on documentation data retention policies based on time.

Any reason to not have data retention policies based on the number of rows?.  It would be really useful to could define something similar to:

```sql
SELECT drop_chunks(rows '1M', 'conditions');
```

So the table will be dropped when the number of rows is bigger than 1 million.

Of course this can be done with a `DELETE` statement (I think) but I don't really know what impact has that related with hypertables.

**Comment by RobAtticus** [comment]
Do you mean where the number of rows in a particular chunk is greater than 1M, or when the total number of rows across chunks is 1M? I guess the latter makes more sense than the former (since you could have weird gaps in your timeline with that approach).

Typically we find people want to keep a certain amount of time when it comes to time-series data, rather than number of rows since that can vary or change as number of devices increase, etc. That said, I don't see why it couldn't be added. Not sure it's high on the roadmap currently, but of course we'd welcome a PR if someone wanted to do it :)

**Comment by RobAtticus** [comment]
One thing to keep in mind is that would be a more expensive operation since we'd have to count the rows in chunks, whereas the time-based data retention has a metadata table for quick lookup of which chunks to drop.

**Comment by jfcalvo** [comment]
> Do you mean where the number of rows in a particular chunk is greater than 1M, or when the total number of rows across chunks is 1M?

I mean the number of rows across chunks. So I can define retention policies based in the number of rows and not only time based.

**Comment by mfreed** [comment]
Closing this out for now - 

* This model isn't a good fit for time-based chunking (although presumably you can build a model of this if you mis-use the time column for integer-based counting.
* User-defined actions and automation in 2.0 could allow users to build some model of this, or at least DELETE upon a certain number of rows.
