### ISSUE TITLE
Are multiple access nodes possible?

### ISSUE THREAD

**Issue by alexandnpu** [timescale/timescaledb#2852]
According to current document below:

https://docs.timescale.com/latest/getting-started/setup-multi-node-basic

A multi-node TimescaleDB implementation consists of:

- One access node to handle ingest, data routing and act as an entry point for user access;
- One or more data nodes to store and organize distributed data.

it seems to me that there can be only one access node for one cluster.

my question is whether multiple access nodes are possible?

thanks

**Comment by k-rus** [comment]
@alexandnpu You are correct, only one access node is supported per cluster. You might be able to use read replica of access node if you setup a streaming/logical replication of it.

**Comment by erimatnor** [comment]
@alexandnpu It might also be possible to setup multi-master replication for the access node, e.g., using BDR: https://www.2ndquadrant.com/en/resources/postgres-bdr-2ndquadrant/

But this is something we have yet to test and officially support. We are considering future enhancements to scale the access node, but nothing has been announced at this time. 

Closing since answered.

**Comment by alexandnpu** [comment]
@k-rus @erimatnor , Really thanks for your reply and info, I will give a look at them
