### ISSUE TITLE
Refresh continuous aggregate in a trigger

### ISSUE THREAD

**Issue by fadimki** [timescale/timescaledb#2983]
I have a trigger function that refreshes multiple views, some are normal Postgres materialized views and one is a timescaledb continuous aggregate.

Now I get the error 
`refresh_continuous_aggregate() cannot run inside a transaction block`

What options do I have so a trigger refresh the continuous aggregate and then my other views?

**Comment by erimatnor** [comment]
Currently, you cannot run refresh in a transaction block, because, technically, there refresh is internally run over two separate transactions. We recommend that you set up a policy to refresh the continuous aggregate at regular intervals.

Related to https://github.com/timescale/timescaledb/issues/2876. As mentioned in that issue, we might consider adding support for refreshing in a transaction block in a later release. In the meantime, there's an experimental and (unofficially supported) version of the refresh function called `_timescaledb_internal.refresh_continuous_aggregate()`, which refreshes based on a chunk in the original hypertable (i.e., it uses the time range of the chunk). I believe this function should work in a transaction block if that helps.
