### ISSUE TITLE
Continuous aggregates parsed as views in psql

### ISSUE THREAD

**Issue by hakanensari** [timescale/timescaledb#2994]
**Relevant system information:**
 - OS: Linux Ubuntu 20.04
 - PostgreSQL version: 13.2
 - TimescaleDB version: 2.1.0
 - Installation method: Docker

**Describe the bug**
This is a cosmetic issue, but in psql, continuous aggregates currently parse as a view instead of materialized view when listing objects.

**To Reproduce**
Connect with psql to a database that has a continuous aggregate. List views with `\dv` and materialised views with `\dm`.

<img width="598" alt="Screenshot 2021-03-02 at 16 46 25" src="https://user-images.githubusercontent.com/31693/109684505-3d51e000-7b78-11eb-9f8e-bfada83b7b7e.png"> 

**Actual behavior**
Continuous aggregates show up under `\dv`.

**Expected behavior**
Continuous aggregates should appear under `\dm` and their type should be materialized view.

**Comment by erimatnor** [comment]
@hakanensari Unfortunately, this is a side-effect of how continuous aggregates are implemented and the limitations of PostgreSQL in terms of being able to define you own object types.

A continuous aggregate is neither a view or a materialized view; it's its own thing. We chose to override the API for materialized views for creation since conceptually a continuous aggregate is close to a materialized view. However, the user facing object is a regular view because a continuous aggregate is actually implemented by multiple internal objects (several views, and a table/hypertable). But we don't have the ability to make `psql` understand this without forking the client.

Hence, this is going to be a limitation until we come up with another way of representing a continuous aggregate internally. One idea is to use a materialized view with a custom table access method. But this is probably quite far off.
