### ISSUE TITLE
Access Node doesn't display tablespace details of Data Nodes

### ISSUE THREAD

**Issue by emres** [timescale/timescaledb#3027]
**Relevant system information:**
 - OS: Debian GNU/Linux 10.8 "buster"
 - PostgreSQL version (output of `postgres --version`): 12.6
 - TimescaleDB version (output of `\dx` in `psql`): 2.1.0
 - Installation method: "apt install"

**Describe the bug**
In the multi-node version (2.1.0), the **Access Node** displays `NULL`s for `chunk_tablespace` even if the tablespaces are properly configured and working fine on **Data Node**s.   

Apparently Access Node isn't aware of the tablespaces configured on Data Nodes, but Data Nodes could be queried by the Access Node to retrieve that information.

**To Reproduce**

1. Install TimescaleDB 2.1.0 with one Access Node and 2 Data Nodes.
2. Create a database with at least one distributed hypertable, (e.g. `conditions` table)
2. Create one tablespace on each data node and attach them to the database (manually) on each data node.
3. INSERT some data to the distributed hypertable via Access Node to make sure the tablespaces are used by PostgreSQL.
3. Then query the TimescaleDB via **Access Node**:

```sql
select
	c.hypertable_name,
	c.chunk_name,
	c.chunk_tablespace ,
	c.data_nodes
from
	timescaledb_information.chunks c
where
	hypertable_name = 'conditions';
```

**Expected behavior**
I'd expect to see the correct tablespace information for each data node.

**Actual behavior**
I see `NULL`s,: Access Node doesn't retrieve the related tablespace information from the data nodes:

```sql
|hypertable_name|chunk_name            |chunk_tablespace|data_nodes|
|---------------|----------------------|----------------|----------|
|conditions     |_dist_hyper_1_1_chunk |                |{ts-dn-01}|
|conditions     |_dist_hyper_1_2_chunk |                |{ts-dn-02}|
|conditions     |_dist_hyper_1_3_chunk |                |{ts-dn-01}|
|conditions     |_dist_hyper_1_4_chunk |                |{ts-dn-02}|
|conditions     |_dist_hyper_1_5_chunk |                |{ts-dn-02}|
|conditions     |_dist_hyper_1_6_chunk |                |{ts-dn-01}|
|conditions     |_dist_hyper_1_7_chunk |                |{ts-dn-01}|
|conditions     |_dist_hyper_1_8_chunk |                |{ts-dn-02}|
|conditions     |_dist_hyper_1_9_chunk |                |{ts-dn-01}|
|conditions     |_dist_hyper_1_10_chunk|                |{ts-dn-02}|
```

But the data is distributed correctly to the Data Nodes via Access Node, and then each data node puts data in the directory associated with the attached tablespace. 

**Additional context**
The original Slack conversation is at: https://timescaledb.slack.com/archives/CPSD82EMU/p1615565024152300 

I opened this issue based on the suggestion of @k-rus .

**Comment by erimatnor** [comment]
Related to #2157

I'll also provide some additional context to the current behavior.

* There is currently no metadata related to tablespaces kept on the access node. Keeping such metadata is problematic since moving a chunk from one tablespace to another on a data node may not be reflected on the access node, unless the metadata kept there is also updated.
* Alternatively, we could fetch the tablespace used by a chunk when we query the view. However, it was decided that views should be fast and not do remote function calls (which also has issues if nodes are down)
* A chunk can have multiple replicas, which each can exist on separate tablespaces. We'd need a good way to show this or show each replica chunk as a unique chunk (which has issues by itself since it can confuse users)

Since the above issues are unresolved, the view currently shows NULL to indicate that we do not yet have a good way to handle tablespace information for remote chunks.

**Comment by svenklemm** [comment]
multinode has been removed
