### ISSUE TITLE
Continuous Aggregation Refresh takes long time for even small volume of data

### ISSUE THREAD

**Issue by BilalS10** [timescale/timescaledb#3054]
This is regarding the continuous aggregation and refreshing it.

We ran the following queries and noted the observations.

1. Creating a table and converting it into hypertable with proper primary keys and indexes.

```
CREATE TABLE "devices_data"(
    time  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    device_id  INTEGER,
    temperature  DOUBLE PRECISION,
    PRIMARY KEY(time, device_id)
);
```
`SELECT create_hypertable('devices_data', 'time');`
`CREATE INDEX ON "devices_data"(device_id, time DESC);`

2. Create a continuous aggregation view to aggregate hourly data and define a refresh policy.

```
CREATE MATERIALIZED VIEW devices_data_summary_hourly
WITH (timescaledb.continuous) AS
SELECT device_id,
       time_bucket(INTERVAL '1 hour', time) AS bucket,
       AVG(temperature),
       MAX(temperature),
       MIN(temperature),
	   SUM(temperature),
	   COUNT(*)
FROM devices_data
GROUP BY device_id, bucket
WITH NO DATA;
```

```
SELECT add_continuous_aggregate_policy('devices_data_summary_hourly',
    start_offset => NULL,
    end_offset => INTERVAL '1 h',
    schedule_interval => INTERVAL '1 minute');
```
    
3. Next we will add some data spanning 4 years for a particular device id.

```
INSERT INTO devices_data
SELECT time, 1, random()*50 + 10
FROM generate_series(TIMESTAMP '2017-03-01 00:00:00',
                  TIMESTAMP '2021-03-01 00:00:00',
             INTERVAL '5 seconds') AS time;
```
 
_query o/p : INSERT 0 25246081
Query returned successfully in 3 min 58 secs._

4. Next we will observe how much time does the refresh job take to add these points to the hourly aggregated view

**refresh job time -> 19.078569 seconds
select count(*) from devices_data_summary_hourly -> 35065**

5. Next we will add data for one device id but just one point per day for 4 years.

```
INSERT INTO devices_data
SELECT time, 2, random()*50 + 10
FROM generate_series(TIMESTAMP '2017-03-01 00:00:00',
                  TIMESTAMP '2021-03-01 00:00:00',
             INTERVAL '1 day') AS time;
```
             
_query o/p : INSERT 0 1462
Query returned successfully in 555 msec._

6. Next we will observe how much time does the refresh job take to add these points to the hourly aggregated view

**refresh job time -> 19.059796 seconds
select count(*) from devices_data_summary_hourly -> 36527**

Brief Observations :

**Output of step  3 & 4 :
Points added to main hypertable -> 25246081
Refresh job time to add these points to CAGG -> 19.078569 seconds
Points added to CAGG -> 35065**

**Output of step 5 & 6 :
Points added to main hypertable -> 1462
Refresh job time to add these points to CAGG -> 19.059796 seconds
Points added to CAGG -> 1462**

Conclusion : 

By observing the output of step 3 and 4, we see that the CAGG takes almost same time to calculate the aggregations even though there is a huge difference in the volume of data.
This potentially means, that timescaledb refreshes the entire dataset spanning 4 years irrespective of the volume of data.

Questions :
1. **Is this how it is supposed to be?**
2. **Does timescaledb just consider the time range and is not intelligent enough to recalculate aggregations only for those points that have changed?**
3. **Are we missing something in our db schema design or any other configurations that is leading to this behaviour?**

**Comment by erimatnor** [comment]
@BilalS10 Can you please provide information on which version of PostgreSQL and TimescaleDB you are using.

**Comment by BilalS10** [comment]
Both are running on the latest version..
Postgresql -> 13.2
TimescaleDB -> 2.1.0

cmd -> select version();
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

cmd -> SELECT extversion FROM pg_extension where extname = 'timescaledb';
 extversion 
------------
 2.1.0
(1 row)

**Comment by erimatnor** [comment]
To answer your questions:

> 1.  Is this how it is supposed to be?

I can only generally say that the volume of data might not always matter that much in terms of how many buckets you must materialize in the continuous aggregate. It doesn't matter if a bucket has just one new value or 1000 new values. You still have to compute a new aggregate value for the bucket. Also, if you haven't previously materialized anything in a range, a refresh will process that range no matter whether there is data there or not since the materializer has never looked at the range before and cannot know it there is data there or not.

> 2. Does timescaledb just consider the time range and is not intelligent enough to recalculate aggregations only for those points that have changed?

It tries to be intelligent about this, but there's a limit to how smart it is. It can only avoid materializing ranges of buckets if those buckets have no new data. So, generally, we try to update only the buckets that have changed, but, if there are many disjoint buckets that have changed, then it is not necessarily faster to do a lot of small materialization compared to one large continuous materialization even though that might materialize more than it strictly has to. We recently added an "unoffical"/experimental variable to control this behavior that you can tweak to see if you get better performance: `timescaledb.materializations_per_refresh_window`. This setting controls how many individual materializations a refresh will do before merging them into one larger materialization. It defaults to 10, but you can set it to, e.g., larger value to see if that improves performance. However, each materialization is a full query, with planning, etc., so I am not sure it will be worth it.

I think one are where we can certainly improve is the efficiency of the actual materialization process. But this is a larger undertaking.

> 3. Are we missing something in our db schema design or any other configurations that is leading to this behaviour?

I don't think so. But your test case is not what continuous aggregates are optimized for; although I am sure we can optimize the materializer for generally faster performance. The first refresh of a range will always process the whole range, and only consecutive refreshes in that range will exclude buckets that have seen no backfill.

**Comment by BilalS10** [comment]
Hi @erimatnor 
Thank you for such a comprehensive answer! I understand that the test case is not what timescale db is optimised for and hence we will probably be tweaking the way we are using the db.

**Comment by erimatnor** [comment]
@BilalS10 closing this for now. Please reopen if it continues to be an an issue and/or new information arises.
