### ISSUE TITLE
Push down DISTINCT to datanodes

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3066]
Currently we do not push down DISTINCT to datanodes which means all processing happens on the access node.
Pushing down DISTINCT would allow to do most of the work on the datanodes.
This pushdown is also requirement for multinode to benefit from skipscan improvement.

**Comment by erimatnor** [comment]
@svenklemm It would be useful to quickly outline how this would work, if you have any insights. Just pushing down `DISTINCT` would not work, unless it is a partitioning key. I guess you'd have to also do `DISTINCT` on the result from each data node.

**Comment by svenklemm** [comment]
Once distinct pushdown is working there should not be much further adjustments provided. The final plan on the access node should like something like this:
```
Unique
  ->  Merge Append
        Sort Key: _hyper_2_1_chunk.dev_name
        ->  Custom Scan (DataNodeScan)
            Unique
                ->  Custom Scan (SkipScan) on _hyper_2_1_chunk
                     ->  Index Scan using _hyper_2_1_chunk_idx on _hyper_2_1_chunk
        ->  Custom Scan (DataNodeScan)
            Unique
                ->  Custom Scan (SkipScan) on _hyper_2_1_chunk
                     ->  Index Scan using _hyper_2_1_chunk_idx on _hyper_2_1_chunk


```

**Comment by nikkhils** [comment]
The following needs to be taken care of:

* Handle both variations of DISTINCT and DISTINCT ON

* The `query->distinctClause` entries should all refer to `TargetEntry` entries which are all from the same relation. If multiple relations are involved then we cannot pushdown

* If plain DISTINCT is used then the columns need to be accessed as per the ordering specified. Right  now the `Remote SQL` fetches columns in attribute number ordering in the table. So if AN is querying the below
```
SELECT DISTINCT col2, col1 from tbl;
```

Then while pushing DISTINCT down to the DN, we need to honor the `col2, col1` ordering. This is because `DISTINCT col1, col2` output is different from `DISTINCT col2, col1` output

*`DISTINCT ON (expr)` is easier to handle in terms of orderings of columns because the expr specifies the ordering explicitly.

**Comment by nikkhils** [comment]
We also need to support pushdown of `SELECT DISTINCT` when `timescaledb.enable_per_data_node_queries` is disabled.
