### ISSUE TITLE
Not seeing restored data after pg_restore

### ISSUE THREAD

**Issue by einsibjarni** [timescale/timescaledb#3198]
**Relevant system information:**
 - OS: FreeBSD 12.2
 - PostgreSQL version (output of `postgres --version`): 11.11
 - TimescaleDB version (output of `\dx` in `psql`): 2.2.1
 - Installation method: pkg from ports

**Describe the bug**
We got bit by https://github.com/timescale/timescaledb/issues/3136 after upgrading to 2.2.0. Our workaround was to do a pg_dump and then downgrade to timescaledb 2.0.1 with an empty DB. After 2.2.1 was released, we upgraded first to 2.2.0, did a pg_restore and then upgraded to 2.2.1. It's working, no seg faults, but no data from before the downgrade.

**To Reproduce**
1. pg_dump from v. 2.2.0
2. Downgrade to v.2.0.1
3. Upgrade to v.2.2.0
4. pg_restore from previous pg_dump
5. Upgrade to v.2.2.1

**Expected behavior**
We should have data from the previous pg_dump in the db.

**Actual behavior**
No data from the previous pg_dump in db.

**Comment by erimatnor** [comment]
@einsibjarni Did you follow the procedure for pg_dump/pg_restore: https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/?

Note also that restoring across extension versions (especially major and minor ones) is not guaranteed to work given that every extension update runs a script that can modify metadata tables in the extension (there's a not about this in the docs link above). So, you might be restoring data that doesn't match the extension version you are using. 

I recommend restoring the data into a database running the same extension version (2.2.0) then upgrade to 2.2.1, which should include the fix for the issue you ran into. 

If this doesn't resolve your issue, feel free to reopen it.

**Comment by einsibjarni** [comment]
Yes, I followed the procedure absolutely. I knew about restoring across extension versions, which is why I first upgraded back to 2.2.0, then did the restore, and only then upgraded to 2.2.1. 

It could be a problem that I followed the procedure, but I was restoring into a non-empty DB. The DB is used by Zabbix server, maybe I could try to restore only the history_* and trends_* tables. Any tips?
