### ISSUE TITLE
Add parameter if_not_exists to add_job

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#3296]
In order to support executing `add_job` speculatively in scripts or other similar situations, it is useful to have a parameter `if_not_exists`. This would only create the job if it does not already exists.

**Comment by mkindahl** [comment]
It is unclear when a job would be considered a duplicate, so closing this issue. Please reopen if you can provide an example of how this would be used.

**Comment by Patanouk** [comment]
Commenting here, since we had the same issue

We have an sql file being run multiple times over the same timescaledb instance
A `SELECT add_job(...)` would add the same job multiple times in that case

In our case, a  job is considered duplicated if another job exists with the same `proc_name` and the same `config` in the `timescaledb_information.jobs` table

That said, I can also imagine use cases where the deduplication as explained above wouldn't work

**Comment by Patanouk** [comment]
Thx for reopening
Just to clarify, we rolled our own postgresql function for this, so this is not asking for a feature request :)

I would also be happy to help make a PR if first timers are welcome

**Comment by konskov** [comment]
Thank you for offering to contribute. We are not very clear on your use case but a PR could make that more clear to us. We would be happy to review.
