### ISSUE TITLE
Continuous aggregates takes lot of disk space

### ISSUE THREAD

**Issue by ricardo-s-ferreira** [timescale/timescaledb#3325]
**Relevant system information:**
 - OS:  x86_64-pc-linux
 - PostgreSQL version: 12.7 
 - TimescaleDB version: 2.3.0
 - Installation method: "using Docker"

**Describe the bug**
Continues aggregate materialized hypertable has one record per chunk of raw data. If the row table has chunks hourly the daily materialized hypertable contains 24 records.
In a huge database this takes a lot of disk space, index are bigger, and queries last longer because there are more blocks to read from disk. I expect to have just one record as in the materialized view.

**To Reproduce**
1. Create a table
```
CREATE TABLE conditions 
(
  TIME TIMESTAMPTZ NOT NULL,
  device        INTEGER NOT NULL,
  temperature   FLOAT NOT NULL,
  PRIMARY KEY (TIME,device)
);
SELECT create_hypertable('conditions', 'time');
```

2. Change time chunk to 1 hour
`SELECT set_chunk_time_interval('conditions', INTERVAL '1 hours');`

3. Create materialized view with time bucket 1 day

```
CREATE MATERIALIZED VIEW conditions_summary_day WITH 
(timescaledb.continuous)
AS
SELECT device, time_bucket(INTERVAL '1 day', TIME) AS bucket, count(*) as reports, avg(temperature), max(temperature), min(temperature)
FROM conditions
GROUP BY device, bucket;
```

4. Insert data
```
INSERT INTO conditions(TIME, device, temperature)VALUES('2021-06-01 10:01:00', 1, 10);
INSERT INTO conditions(TIME, device, temperature)VALUES('2021-06-01 19:01:00', 1, 10);
```

5. Call aggregation
`CALL refresh_continuous_aggregate('conditions_summary_day', '2021-06-01', '2021-06-02');`

6. chek the name of hypertable
`SELECT * FROM timescaledb_information.continuous_aggregates;`

**Expected behavior**
The query from materialized hypertable should return just one record
`select count(*) from _timescaledb_internal._materialized_hypertable_2;`
like when you query the view
`select count(*) from conditions_summary_day;`

**Actual behavior**
The query returns 2 records
`select count(*) from _timescaledb_internal._materialized_hypertable_2;`
however quering the materialized view returns just one, as expected.
`select count(*) from conditions_summary_day;`

**Comment by NomAnor** [comment]
Hi,
the materialized hypertable has an additional column `chunk_id` so it contains a row of aggregated data (not the final result but an intermediate representation) per chunk. In the view itself these rows then get grouped and finalized with the `finalize_agg()` function.

I also think this wastes space and time. I read somewhere this is because of distributed hypertables which spread chunks over multiple servers and then the finalization is run on a central node.

I would like to see an option to disable this and store the final results if you don't use distributed hypertables.

It takes more space because the intermediate representation for `AVG`, `VAR` and `STDEV` stores a tuple of three floats/doubles instead of only one value for the result.  See https://github.com/postgres/postgres/blob/29854ee8d1ca4a46adb7e84deb17e6fb18e531cc/src/backend/utils/adt/float.c#L2815 and https://github.com/postgres/postgres/blob/ad2da246c69dd5ec55764d4b6066f3b0c0d24ca2/src/include/catalog/pg_aggregate.dat#L40

It takes more time because of the grouping and finalization.

I have not tested if there is a real difference but maybe someone else has more information.

**Comment by NomAnor** [comment]
I had a look into our data. I seems the aggregate tables are twice as big as "necessary" (data is at the end).

The current implementation is unavoidable if aggregates are calculated per chunk because the chunk results must be merged and this is what the intermediate representation is designed to do. For distributed hypertables this is needed, for non-distributed tables maybe. It would be nice to have the option to store the finalized results, but this complicates the implementation.

I can't recreate the problem with the query I mentioned. I think it had to do with not pushing some conditions down to the underlying table and then causing unnecessary sort steps. This might be fixed in v2 (currently running v2.2 on postgresql 13).

### Data sample
Here is a rough overview of my test sample. The database contains measurements from many independent sensors with one measurement per row, the columns are roughly `timestamp, device_id, value` and some smallints.

#### Raw Data
Time Range: `2019-01-03 UTC` to `2019-01-31 UTC`
Raw data rows: 247 120 373
Indexes over `(timestamp)` and `(smallint, timestamp)`

The hypertable has a chunk size of one week:
```
chunk_name          | range_start            | range_end              | table_bytes | index_bytes | toast_bytes | total_bytes |
--------------------+------------------------+------------------------+-------------+-------------+-------------+-------------+
_hyper_32_950_chunk | 2019-01-03 01:00:00+01 | 2019-01-10 01:00:00+01 | 3541 MB     | 3173 MB     | 8192 bytes  | 6714 MB     |
_hyper_32_951_chunk | 2019-01-10 01:00:00+01 | 2019-01-17 01:00:00+01 | 3454 MB     | 3096 MB     | 8192 bytes  | 6549 MB     |
_hyper_32_952_chunk | 2019-01-17 01:00:00+01 | 2019-01-24 01:00:00+01 | 3732 MB     | 3345 MB     | 8192 bytes  | 7077 MB     |
_hyper_32_953_chunk | 2019-01-24 01:00:00+01 | 2019-01-31 01:00:00+01 | 3474 MB     | 3113 MB     | 8192 bytes  | 6587 MB     |
--------------------+------------------------+------------------------+-------------+-------------+-------------+-------------+
                                                                      |  14 GB      | 12 GB       | 32 kB       | 26 GB       |
                                                                      +-------------+-------------+-------------+-------------+
```

#### Aggregates
Continious aggregates over bucket sizes of day, hour and minute with aggregate columns `bucket, count, min_timestamp, max_timestamp, min_value, max_value, avg_value, stddev_value`
Index over three smallints and the bucket timestamp.

I created two new tables from the current aggregates, one from the view, one from the materialized hypertable:
```
CREATE TABLE public.data_day AS SELECT * FROM our_schema.data_day WHERE "bucket" >= '2019-01-03 UTC'::timestamptz AND "bucket" <= '2019-01-31 UTC'::timestamptz - '1 day'::INTERVAL;
CREATE TABLE public.data_day_mat AS SELECT * FROM "_timescaledb_internal"."_materialized_hypertable_38" WHERE "bucket" >= '2019-01-03 UTC'::timestamptz AND "bucket" <= '2019-01-31 UTC'::timestamptz - '1 day'::INTERVAL;
```
##### Number of rows
```
table              | rows     | row_mat  |
------------------ +----------+----------+
public.data_day    | 18754    | 18754    |
public.data_hour   | 448372   | 448372   |
public.data_minute | 11269583 | 11269583 |
```
The bucket sizes are all smaller than the chunk size so only one row per chunk so both tables have the same number of rows. This means a final merge is not strictly necessary.

##### Table sizes
```
table              | table_size | index_size | total_size | table_size_mat | index_size_mat | total_size_mat | total_ratio        |
-------------------+------------+------------+------------+----------------+----------------+----------------+--------------------+
public.data_day    | 2040 kB    | 760 kB     | 2800 kB    | 5048 kB        | 760 kB         | 5808 kB        | 2.0742857142857143 |
public.data_hour   | 47 MB      | 17 MB      | 64 MB      | 117 MB         | 17 MB          | 134 MB         | 2.0897373540856030 |
public.data_minute | 1174 MB    | 437 MB     | 1611 MB    | 2936 MB        | 437 MB         | 3372 MB        | 2.0932729424087833 |
```
##### Bytes per row
```
table              | table | index | table_mat | index_mat |
-------------------+-------+-------+-----------+-----------+
public.data_day    | 109   | 40    | 273       | 40        |
public.data_hour   | 109   | 40    | 273       | 40        |
public.data_minute | 109   | 40    | 273       | 40        |
```
Both have the same index so the index size stays the same. But because the materialized hypertable stores the intermediate representation as `bytea` the rows are bigger. All aggregates store the same columns so the sizes between them are all the same.


The difference is not that bad. We have data from almost 20 years (month from over five years are way smaller), currently sitting at ca. 2TB. This is not an enterprise system, so reading a smaller table from slow hdds might be helpful but I lack the expertiese to do proper  profiling.

**Comment by gayyappan** [comment]
@NomAnor Thank you for the excellent analysis.  This is on our road map - we are looking into ways to mitigate this issue.

**Comment by RafiaSabih** [comment]
Closing, since the new CAgg from v2.7 solves this.
