### ISSUE TITLE
Real-time continuous aggregate DAY-bucket gets stale after refresh. Difference in behaviour with HOUR.

### ISSUE THREAD

**Issue by WaatzeG** [timescale/timescaledb#3361]
**Relevant system information:**
 - OS: Arch Linux
 - PostgreSQL version: 12.7
 - TimescaleDB version): 2.3.0
 - Installation method: Docker timescale/timescaledb:latest-pg12

**Describe the bug**
A continuous aggregate with an interval of DAY gets stale and inconsistent after refreshing with an `end_offset` that is within the current bucket. It gets updated only after a manual or policy refresh. It does not return raw data from the hypertable for this bucket anymore, even though it is a real-time continuous aggregate.

The HOUR bucket does not show this behavior. The current HOUR does not get materialized and querying the continuous aggregate keeps returning the raw data from the hypertable, as expected.

I don't understand why the HOUR bucket isn't materialized, while the DAY is. I would have expected the same behavior for both.

**To Reproduce**
Make sure you execute this a few minutes after the full hour.
1. create the hypertable and views
```
CREATE TABLE test (
    id text NOT NULL,
    timestamp timestamptz NOT NULL,
    value double precision
);

SELECT create_hypertable('test', 'timestamp');

CREATE MATERIALIZED VIEW test_hour
WITH (timescaledb.continuous) AS
SELECT id,
       time_bucket(INTERVAL '1 hour', timestamp) AS bucket,
       SUM(value)
FROM test
GROUP BY id, bucket
WITH NO DATA;

CREATE MATERIALIZED VIEW test_day
WITH (timescaledb.continuous) AS
SELECT id,
       time_bucket(INTERVAL '1 day', timestamp) AS bucket,
       SUM(value)
FROM test
GROUP BY id, bucket
WITH NO DATA;
```
2. insert test data and refresh. The timestamp is earlier than the end_offset of the refresh so it should be part of the refresh.
```
insert into test values ('1', now() - interval '2 minute', 1.0);
CALL refresh_continuous_aggregate('test_hour', INTERVAL '6 months' , INTERVAL '1 minutes');
CALL refresh_continuous_aggregate('test_day', INTERVAL '6 months' , INTERVAL '1 minutes');
```

3. check contents of continuous aggregate. Still OK.
```
select * from test_hour; -- value = 1.0 as expected
select * from test_day; --value = 1.0 as expected
```

4. add another value. The timestamp is in the future and check: NOT OK
```
insert into test values ('1', now() + interval '2 minute', 1.0);
```

```
select * from test_hour; -- value = 2.0 as expected
select * from test_day; --value = 1.0 ??? Should be 2.0. It was materialized and the new data was ignored?
```
Checked the contents of the `_timescaledb_internal._materialized_hypertable_...` for both the `test_day` and `test_hour` aggregates and the `test_hour` doesn't contain a value while `test_day` does for "2021-06-24 00:00:00+00" 

**Expected behavior**
I expected `test_day` to have a value of 2.0 as well. I believe I read that if the bucket-to-aggregate isn't finished yet before the `end_offset`, it shouldn't be materialized and should be aggregated ad-hoc from the raw data. The `test_day` aggregate is materialized before the day is over and new raw data is ignored.

I can't explain the difference in behavior between HOUR and DAY buckets. Both of them aren't finished at the time of refreshing, but the DAY bucket is materialized, while the HOUR isn't.

**Actual behavior**
The `test_hour` continuous aggregate remains to be real-time and consistent, while the `test_day` aggregate gets stale and inconsistent until refresh.

**Comment by erimatnor** [comment]
A continuous aggregate only materializes full buckets. Real-time aggregation unions the materialized buckets with non-materialized buckets. So, what I suspect is happening is that the refresh of the day aggregate doesn't materialized the recent bucket because the refresh range you specify isn't covering the entire bucket, while in the hour case it does (since the bucket is much smaller it is more likely to fit within your end of the range).

Thus, when you insert the new data it will fall into a non-materialized bucket in one case and a materialized bucket in the other case. Therefore, the new value isn't accounted for until the next refresh.

When using real-time aggregation it is recommended that you do not refresh recent buckets for this reason. Any backfill won't be visible until the next refresh if it falls into an already materialized bucket. By keeping the most recent buckets unmaterialized, you will reduce the likelihood of having an insert fall into a materialized bucket that requires a refresh.

Please reopen this issue if this doesn't explain the cause of the behavior you are seeing.

**Comment by WaatzeG** [comment]
Thanks taking the time to look at this issue @erimatnor. I'm re-opening this issue because I think you might have misunderstood the problem.

In the reproduction examples I supplied, I added manual refreshes with a range that ends mid-day. Because the refresh range ends mid-day, it means the current day should never be materialized. In my example you can see that the current day *is* materialized and that causes the real-time continuous aggregate not to be real-time anymore.

This behavior seems different for hours than day intervals. The current hour isn't materialized, but the current day is.
