### ISSUE TITLE
creating chunk after deletion

### ISSUE THREAD

**Issue by Rashid987** [timescale/timescaledb#340]
after deleting a particular chunk i have changed the time_interval but when i am trying to create chunk on the same Timestamp it taking the old time interval.any way for timestamp older than the deleted one it's creating chunk with new time interval.

**Comment by RobAtticus** [comment]
How did you delete the chunk? `DROP TABLE` on the table inside `_timescaledb_internal`, using `drop_chunks`, or did you just delete all the rows that went into the table?

**Comment by Rashid987** [comment]
i have used drop table on the table inside _timescaledb_internal

**Comment by RobAtticus** [comment]
So that won't work because TimescaleDB keeps metadata tables that store the constraints for each chunk, which will remain if you don't drop the chunk via one of our APIs (e.g. `drop_chunks`). In general it is probably not a good idea to manipulate the chunk tables directly, it can lead to your database being in a weird state.

**Comment by cevian** [comment]
@Rashid987 actually drop table should work correctly to drop metadata related to the chunk. But because of multi-dimension partitioning we "remember" that time period for the old chunks and re-use it when creating new chunks. We may consider changing this. Can you describe your use case for this functionality?

**Comment by Rashid987** [comment]
in my database i have started it with default time interval 1 month after
that i have changed it to one day.now i have one chunk_table with 1 month
time interval i want to change that chunk_tables of one for that time
period so i have tried to backup that time chunk data and drop chunk and
again inserting that data. But it's creating new chunk_table with 1 month
time interval.

**Comment by RobAtticus** [comment]
Hey @Rashid987 , this should be fixed in 0.9.0 which went out recently. Please let us know if you run into any other issues and feel free to close if resolved.
