### ISSUE TITLE
Chunk expanding on disk even with vacuum

### ISSUE THREAD

**Issue by jameswinegar** [timescale/timescaledb#3449]
**Relevant system information:**
Timescale AMI

**Describe the bug**
Vacuum full on a chunk leaves dead tuples, eats storage.

**To Reproduce**
Unable to reproduce issue

**Expected behavior**
Vacuum removes tuples

**Actual behavior**
We had a table lock issue caused by another query, table space exploded to 300 GB for the chunk. Vacuum Full was executed against the chunk, reducing it to our expected ~50 GB chunk size.  Afterwards compression was applied per the compression policy. The table space continues to balloon over time with no writes to the chunk (I'm 99% sure as i control the writer process). Screenshot below is after doing a vacuum full a second time, I can add an additional one in ~12 hours. 

The impact is that with 300 GB for this chunk, we grow past the memory limit for keeping data in the buffer cache and take a huge performance hit. 

**Screenshots**
```
machine_data=# VACUUM FULL VERBOSE _timescaledb_internal._hyper_9_288_chunk;
INFO:  vacuuming "_timescaledb_internal._hyper_9_288_chunk"
INFO:  "_hyper_9_288_chunk": found 0 removable, 0 nonremovable row versions in 0 pages
DETAIL:  0 dead row versions cannot be removed yet.
CPU: user: 0.04 s, system: 0.00 s, elapsed: 0.04 s.
VACUUM
machine_data=# SELECT relname, n_dead_tup FROM pg_stat_user_tables order by n_dead_tup desc limit 3;
      relname       | n_dead_tup
--------------------+------------
 _hyper_9_288_chunk |   46924134
 _hyper_9_327_chunk |     258550
 _hyper_9_322_chunk |      54426
(3 rows)
```

```
machine_data=# VACUUM FULL VERBOSE _timescaledb_internal._hyper_9_288_chunk;
INFO:  vacuuming "_timescaledb_internal._hyper_9_288_chunk"
INFO:  "_hyper_9_288_chunk": found 46924134 removable, 0 nonremovable row versions in 4363521 pages
DETAIL:  0 dead row versions cannot be removed yet.
CPU: user: 12.65 s, system: 14.27 s, elapsed: 26.94 s.
VACUUM
machine_data=# SELECT relname, n_dead_tup FROM pg_stat_user_tables order by n_dead_tup desc limit 3;
      relname       | n_dead_tup
--------------------+------------
 _hyper_9_288_chunk |   46924134
 _hyper_9_327_chunk |     258550
 _hyper_9_322_chunk |      54426
(3 rows)
```

**Additional context**
I am able to handle this by just running vacuum full regularly (2x daily) against the chunk, and it will eventually fall off by retention policy; however, I'd like to be able to maintain these types of issues.

**Comment by nikkhils** [comment]
@jameswinegar `VACUUM FULL` is typically not recommended since it has performance implications. The chunk is exclusively locked during the operation. The process also makes a full copy of the chunk, which requires extra disk space when it runs. If needed, one should use periods of lowest database activity for it.

One option here is to make `autovacuum` settings aggressive for this specific `_hyper_9_288_chunk` table. It can be done by issuing following commands:

~~~sql
ALTER TABLE _timescaledb_internal._hyper_9_288_chunk SET (autovacuum_vacuum_scale_factor = 0.0);
ALTER TABLE _timescaledb_internal._hyper_9_288_chunk SET (autovacuum_vacuum_threshold = 100000);
ALTER TABLE _timescaledb_internal._hyper_9_288_chunk SET (autovacuum_analyze_scale_factor = 0.0);
ALTER TABLE _timescaledb_internal._hyper_9_288_chunk SET (autovacuum_analyze_threshold = 100000);
~~~

Please see if this helps and does away with the need of using `VACUUM FULL` on this chunk. You might have to fiddle around with the threshold numbers to see which ones work best for you. Here I have used 100000 dead tuples as the trigger for the autovacuum/analyze.

**Comment by jameswinegar** [comment]
Thanks for the advice, for our use case the most recent 4 chunks are the most important so the `VACUUM FULL` wasn't terrible, but also not great.

I've added the auto_vacuum changes, I appreciate it a lot.

**Comment by nikkhils** [comment]
Please feel free to open another issue if you have any further queries.
