### ISSUE TITLE
Enhance GRANT/REVOKE handling

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#3535]
Carrying this over to `timescaledb` project from https://github.com/timescale/product/issues/63

- [x] Test the behavior of SET SESSION AUTHORIZATION or SET ROLE in multi-node. Currently it sets the AN session current user/role which should create connections with the same user to the DNs.
- [x] #3595
- [x] #3594
- [x] https://github.com/timescale/timescaledb/issues/3851
- [x] `REVOKE  ALL ON public.test  FROM regress_dep_user2;` works, but `REVOKE ALL ON ALL TABLES IN SCHEMA testns   FROM  regress_dep_user2;` doesn't work. We can use the same logic as (2) and decide to forward.

To be handled later:
- https://github.com/timescale/timescaledb/issues/3850

**Comment by erimatnor** [comment]
FWIW, I am not sure we can blindly forward `GRANT ALL ON SCHEMA public.test` since that will make the command fail if it doesn't exist on all nodes and then there's no way to get out of the failure. I think we need to be smart about how to forward commands, for instance, we could check if any distributed hypertables or objects belonging to a distributed hypertable exist in the schema. Only if such objects exists, we should forward the command.

**Comment by erimatnor** [comment]
@nikkhils @pmwkaa Can you update the status of the three uncompleted checkboxes above? Are these still valid, should they be worked on, or are they no longer applicable?

**Comment by nikkhils** [comment]
#3850 will be handled later. Erik has submitted a patch for #3851. SO we are almost there with this

**Comment by NunoFilipeSantos** [comment]
Done.
