### ISSUE TITLE
Build fails on older OS (e.g., CentOS 6.8), older versions of gcc

### ISSUE THREAD

**Issue by baiyinqiqi** [timescale/timescaledb#37]
Hi,
    gcc version:4.4.7

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -fpic -DINCLUDE_PACKAGE_SUPPORT=0 -MMD -I. -I./ -I/usr/local/postgresql-9.6.2/include/server -I/usr/local/postgresql-9.6.2/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/metadata_queries.o src/metadata_queries.c
In file included from src/metadata_queries.c:14:
src/chunk.h:23: error: redefinition of typedef ‘Chunk’
src/metadata_queries.h:6: note: previous declaration of ‘Chunk’ was here
make: *** [src/metadata_queries.o] Error 1

**Comment by cevian** [comment]
Hi @baiyinqiqi I looked into this. The change in `gcc` for allowing redeclarations was added quite a while ago ([commit](https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=ce3765bf44e49ef0568a1ad4a0b7f807591d6412)) and I know this compiles in `centos` 7. So I have a question for you: would it be hard for you to upgrade `centos` or `gcc`? 

Our dilemma is that if we fix these series of compilation errors for you, we won't be able to guarantee that other compilation bugs don't crop up because our CI system does not run a `gcc` version that old. So, we will fix this if you need it but were wondering what the alternatives were on your end.

**Comment by baiyinqiqi** [comment]
unfortunately，it's difficult for us that if we upgrade centos or gcc.The most important reason is ,the server is not belong to us and we just use it.but i will try it again on our own server.
thank for your pretty job.

**Comment by mfreed** [comment]
Removing bug label, as this is more an "enhancement" question of whether we want to support old gcc versions.
