### ISSUE TITLE
Altering the number of space partitions

### ISSUE THREAD

**Issue by haohello** [timescale/timescaledb#374]
`CREATE TABLE one_min_bars (
tm   TIMESTAMPTZ    NOT NULL,
code VARCHAR(15) NOT NULL,
open DECIMAL NOT NULL,
close DECIMAL NOT NULL,
high DECIMAL NOT NULL,
low DECIMAL NOT NULL,
volume INTEGER NOT NULL,
amount DECIMAL NOT NULL,
PRIMARY KEY (tm, code)
);

SELECT create_hypertable('one_min_bars', 'tm', 'code', 3500);
SELECT set_chunk_time_interval('one_min_bars', 1728000000000); -- SELECT 86400000000*20
CREATE INDEX ON one_min_bars (code, tm DESC);`

The number of partitions for now is 3500, which is the total number of all securities,  so what if later when there are more securities added, how can I alter this number then?

**Comment by mfreed** [comment]
Hi @haohello:

1. We don't currently expose a way to modify the number of partitions to secondary dimensions after they are created.  We do currently allow this for the [primary time dimension](http://docs.timescale.com/latest/api#set_chunk_time_interval), but on our todo for what you ask.

2. That said, space partitions aren't actually designed to be used the way you ask.  They currently use *hash partitioning*, so that each distinct item is mapped (randomly hashed) to an available bucket.  There isn't a 1-to-1 mapping from distinct items to buckets, and we don't recommend trying to use them for that.  See our best practices descriptions for more information:  http://docs.timescale.com/latest/using-timescaledb/hypertables#best-practices

**Comment by mfreed** [comment]
While I believe I answered your immediate question @haohello , I'm going to leave this issue open as a feature request.

**Comment by erimatnor** [comment]
@haohello The ability to set the number of space partitions has been added as part of this PR: https://github.com/timescale/timescaledb/pull/399

The functionality will be part of the next release.

**Comment by RobAtticus** [comment]
Hi @haohello , this functionality went out in 0.9.0 a few days ago. Please let us know if you run into any issues, otherwise feel free to close this issue :)
