### ISSUE TITLE
Do proper Path planning for upper rels in multi-node queries

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3807]
Currently, some multi-node push-down optimizations, such as LIMIT and DISTINCT, are applied at the deparsing stage, rather than first being planned as Upper relation Paths on the data node scan relations.

One reason for this is that earlier PostgreSQL versions didn't have support in the foreign data wrapper (and API) to generate paths for Upper relation kinds.

To properly implement push-down plans, we should generate the appropriate Paths (including their cost) when push-down is requested via partitionwise planning via the following `UpperRelationKind`s:

- `UPPERREL_DISTINCT` - for pushing down distinct queries
- `UPPERREL_ORDERING` - for pushing down sorts
- `UPPERREL_FINAL` - for pushing down things like `LIMIT` and `OFFSET`

Future push-down optimizations might also involve upper relations like `UPPERREL_WINDOW` for pushing down windowing functions.

Once these upperrel Paths are created, the planner will generate the least cost plan, and generating the remote SQL statement will simply be the task of deparsing that plan (for the data node scan) into a SQL statement.

Note that adding the proper Paths is necessary for the planner on the access node to understand what the properties are of the data coming back from data nodes. For instance, in the case of `DISTINCT ON(space_key)` push down, the combined result from all data nodes is already distinct. However, without exposing this in the plan, the access node will always believe it has to execute a `Unique` node on the access node again.

Also note that in recent versions of the `postgres_fdw` some support for ordering and final (LIMIT) push down has been added, so it can provide a blueprint for how to do it. However, it needs to be adapted for the multi-node case. For instance, both DISTINCT and LIMIT push down have different implications when pushing down to multiple nodes compared to a single remote node.

**Comment by nikkhils** [comment]
The costing code has been updated to use the latest from PG14 fdw code base.

However, the `create_partitionwise_grouping_paths` function sets the fdw_private field of the `child_grouped_rel` variable and this is NOT carried to the main UPPER grouped_rel. Because of this issue when we reach the ORDER BY part in `create_ordered_paths`, this grouped_rel does not have `fdw_private` set. So, when it becomes the input rel for the `timescale_create_upper_paths_hook` function we cannot do much because we do not know if this needs to be pushed down to the datanodes. This is a big issue that I am facing currently.

**Comment by svenklemm** [comment]
multinode has been removed
