### ISSUE TITLE
[Bug]: allow_install_without_preload does not work

### ISSUE THREAD

**Issue by ftersin** [timescale/timescaledb#3858]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Background worker, Configuration

### What happened?

By some reason i have to create the extension before restarting of postgresql server.

I install packages and execute:
```
# SET timescaledb.allow_install_without_preload = 'on';
# LOAD 'timescaledb';
# CREATE EXTENSION IF NOT EXISTS timescaledb;
```

But the second command returns
```
INFO:  timescaledb loaded
FATAL:  cannot create PGC_POSTMASTER variables after startup
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
psql (13.5, server 13.4)
```

It seems the reason is variable max_background_workers is registered w/o checking of process_shared_preload_libraries_in_progress. 

Could this be fixed?
If a workaround exists to postpone restarting of postgresql after creating the extension?

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

13.4

### What operating system did you use?

CentOS 7.9 x64

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

**Comment by erimatnor** [comment]
@ftersin Can you explain what it is you are trying to do by not preloading the extension?

There's functionality in the extension that requires preloading so that option to override the preload check isn't really supposed to be used in normal cases.

**Comment by ftersin** [comment]
@erimatnor I want to automatize installation of the extension on single/cluster postgresql instances. But i'd like to change the order of steps - 1) install packages 2) change postgresql config and restart 3) create the extension - to 1) 3) 2)
So i have no aims to use any of the extension features w/o preloading.

**Comment by erimatnor** [comment]
@ftersin I am not sure it is possible to create the extension without preloading, since that would prevent important functionality from being present, like initializing shared memory that can only be done a PostgreSQL start.

I am also unsure the option `timescaledb.allow_install_without_preload` is actually providing the functionality you are looking for. It is not recommended for regular usage as evident by the warning message where it is mentioned. And, I also suspect that the extension has evolved to not allow install without preload, so it might actually make sense to remove that setting. I think it was only used for debugging purposes.

**Comment by ftersin** [comment]
@erimatnor Well, ok. We'll try to rework our solution. Thanks.
