### ISSUE TITLE
[Bug]: Manual refresh breaking realtime continuous aggregate

### ISSUE THREAD

**Issue by deceive3w** [timescale/timescaledb#3877]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

after call refresh_continuous_aggregate make real-time aggregate is not working every inserts new data continuous aggregate not updating

### TimescaleDB version affected

2.3.1

### PostgreSQL version used

13.3

### What operating system did you use?

Mac OS Catalina

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE conditions(
    time TIMESTAMP NOT NULL,
    device_id INTEGER,
    temperature FLOAT,
    humidity FLOAT
);

SELECT * FROM create_hypertable('conditions', 'time', 'device_id', 12);

INSERT INTO conditions values (now(), 1, 1 , 1)

CREATE MATERIALIZED VIEW conditions_summary_hourly
WITH (timescaledb.continuous) AS
SELECT device_id,
       time_bucket(INTERVAL '1 hour', "time") AS bucket,
       AVG(temperature),
       MAX(temperature),
       MIN(temperature)
FROM conditions
GROUP BY device_id, bucket
WITH NO DATA;

SELECT add_continuous_aggregate_policy('conditions_summary_hourly',
    start_offset => INTERVAL '1 month',
    end_offset => INTERVAL '1 h',
    schedule_interval => INTERVAL '1 hour');
	

	
select * from  conditions_summary_hourly order by device_id desc limit 1; 

INSERT INTO conditions values (now(), 2, 2 , 2)

select * from  conditions_summary_hourly order by device_id desc limit 1; -- number changed

call refresh_continuous_aggregate('conditions_summary_hourly', NULL, NULL); -- manual refresh breaking realtime aggreagate

INSERT INTO conditions values (now(), 4, 4 , 4)

select * from conditions -- number is exists in table
select * from  conditions_summary_hourly order by device_id desc limit 1; -- number is not change
call refresh_continuous_aggregate('conditions_summary_hourly', NULL, NULL); -- manual refresh again
select * from  conditions_summary_hourly order by device_id desc limit 1; -- number changed
```

**Comment by mfundul** [comment]
@deceive3w can you reproduce this bug with timescaledb version 2.5.0?

**Comment by deceive3w** [comment]
> @deceive3w can you reproduce this bug with timescaledb version 2.5.0?

still have the same problem

Timesacledb 2.5.0
PostgreSQL 14.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

**Comment by idoberko2** [comment]
Same here, TimescaleDB 2.5.0, PG 13.4

**Comment by mfundul** [comment]
I think there is a fundamental difference between how the code works and how the real-time aggregation feature is advertised.

In this scenario all new INSERTs fall into the same time bucket as the old INSERTs. As far as the code is concerned, those are old since they concern an already materialized time bucket, and they are not part of the UNION for the real-time aggregation.

As far as the user is concerned, those are new data, since they were inserted after the last materialization with a later timestamp, so they should be part of the UNION for the real-time aggregation.

**Comment by afiskon** [comment]
I agree with @mfundul comment. This is a fundamental limitation of the way CAGGs are implemented. The actual problem is that this behavior is not well documented for real-time aggregates.

**Comment by afiskon** [comment]
The PR to the docs https://github.com/timescale/docs/pull/655

**Comment by gayyappan** [comment]
@deceive3w The real time aggregation feature is union of : the materialized data + data from the actual hypertable (for buckets beyond the materialized data ).

Say the hypertable has data for Jan-Dec and you setup a cagg on it.
When you run,
refresh_continuous_aggregate(cagg, NULL,  August 31 2021);  ---> this is the materialized data : everything from Jan to August.

Say, we have an insert into Nov. When we query the real time aggregate view , it will display this since it is beyond the materialized data.

Say, now we  have another insert into August, the real time aggregate does **not** show this as this region is part of already materialized data ( this row is not part of the materialized data since this row was not part of the hypertable when the refresh was executed )
The next time a refresh is executed : the data for august gets materialized and at that point, the real time aggregate would display this new row for August. 

We chose to implement this behavior so that caggs are performant - we do not want to recalculate previously materialized data at query time.

In your example, the manual refresh_continuous_aggregate( cagg, NULL, NULL )  extended the region of the materialized data. As an alternative, you can just run call run_job( job id for refresh policy ). This will respect the refresh policy limits. Hope that helps.

**Comment by deceive3w** [comment]
@gayyappan I got it, so real-time aggregate not working when the materialized region data is greater than data?.

So what should I do when I accidentally call refresh_continuous_aggregate( cagg, NULL, NULL ), is breaking realtime aggregate. how to revert back?

**Comment by idoberko2** [comment]
In my case, I misunderstood the proper usage of CAGGs and did not create a refresh policy at all. It led to very poor performance when querying the CAGG since no data was materialized at all.

@deceive3w I'm not an expert but I think what you're looking for is actually not reverting back but applying a refresh policy that will constantly refresh the materialized data.

**Comment by afiskon** [comment]
Please see the updated docs. They clarify the existing limitations of the CAGGs in more detail https://github.com/timescale/docs/pull/655

**Comment by gayyappan** [comment]
@deceive3w
> So what should I do when I accidentally call refresh_continuous_aggregate( cagg, NULL, NULL ), is breaking realtime aggregate. how to revert back?
You cannot undo a "refresh".  As you keep inserting newer data into the hypertable , the previous materialized data boundary is no longer at the latest timestamp. At this point, the real time aggregate will fetch data from the hypertable. 

As @idoberko2 commented, a refresh policy will automatically keep refreshing the cagg in the background and a manual refresh is not necessary.

Also, preferred usage for manual refresh  is `SELECT refresh_continuous_aggregate( <cagg>, NULL, <specific timestamp>)`  ---> refresh everything from beginning to specific timestamp
OR
`refresh_continuous_aggregate(<cagg>, <start-timestamp>, <end-timestamp>)` ---> refresh cagg for the specific range
