### ISSUE TITLE
[Bug]: Inconsistent time column aliasing between time_bucket and time_bucket_gapfill

### ISSUE THREAD

**Issue by r614** [timescale/timescaledb#3955]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

I encounter this error when running a `time_bucket_gapfill` query: 

```
no top level time_bucket_gapfill in group by clause
```
Example query: 
```sql
SELECT
	time_bucket_gapfill('1 minute', timestamp) AS timestamp,
	symbol AS symbol, 
	exchange AS exchange, 
	locf(symbol) as symbol,
	locf(exchange) as exchange,
	last(price, timestamp) as price,
	last(interest, timestamp) as interest
FROM derivatives
WHERE DATE(timestamp) = CURRENT_DATE
GROUP BY symbol, exchange, timestamp;
```

I can run the same query successfully by replacing `time_bucket_gapfill` with `time_bucket`. 
Miranda on Slack helped me find a workaround by just renaming the time-column alias:

 ```sql
SELECT
	time_bucket_gapfill('1 minute', timestamp) AS time,
    ....
GROUP BY symbol, exchange, time;
```

This workaround is fine for my use-case atm, though I am trying to keep data-types consistent across services, and renaming columns manually is pretty annoying. Not sure if this is a bug either :eyes: 

[Original Slack Thread](https://timescaledb.slack.com/archives/C63MYDZ35/p1641244493370300) 

### TimescaleDB version affected

2.3.0

### PostgreSQL version used

11.12

### What operating system did you use?

Mac OS X 12.0 ARM 

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
no top level time_bucket_gapfill in group by clause
```

### How can we reproduce the bug?

```bash
- Create any table
- Try aliasing the time_bucket_* output column as the same name as your existing time column
```

**Comment by svenklemm** [comment]
This is not a bug and expected behaviour. It's also completely unrelated to timescaledb and postgres has the same behaviour. If you have a column named `timestamp` and a column alias in your query name `timestamp` and you group by `timestamp` you are not grouping by the column alias but the column. In that situation time_bucket_gapfill throws an error because your query does not group by time_bucket_gapfill. So the solution is to use a column alias that is not also a column or repeat the time_bucket_gapfill expression in the group by clause.
