### ISSUE TITLE
[Bug]: time_bucket_ng for daylight saving hour return time from future

### ISSUE THREAD

**Issue by psztoch** [timescale/timescaledb#4392]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill

### What happened?

`SELECT timescaledb_experimental.time_bucket_ng('1 hour'::interval, '2021-10-31 00:00:00+00'::timestamptz, 'Europe/London') AT TIME ZONE 'UTC'` -> `2021-10-31 01:00:00` but should return `2021-10-31 00:00:00`

Most everyone assumes that the time_bucket function returns the begin of the bucket (not time from the middle).

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

13.7

### What operating system did you use?

Debian Bullseye

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

**Comment by afiskon** [comment]
What is your session TZ? Note that `'2021-10-31 00:00:00+00'::timestamptz` uses this particular TZ.

**Comment by afiskon** [comment]
@psztoch  OK, here is what happens.

Note that your argument is `2021-10-31 00:00:00+00'::timestamptz`. By specifying `+00` you overwrote the TZ. This is basically equivalent to `2021-10-31 00:00:00 UTC`, which is `2021-10-31 01:00:00 Europe/London`. Since time_bucket_ng() treats the argument in the provided timezone you got the result `2021-10-31 01:00:00`.

What you probably wanted to do was:

```
40428 (master) =# SET TIME ZONE 'Europe/London';
SET
Time: 0.528 ms
40428 (master) =# SELECT timescaledb_experimental.time_bucket_ng('1 hour'::interval, '2021-10-31 00:00:00 Europe/London', 'Europe/London');
     time_bucket_ng
------------------------
 2021-10-31 00:00:00+01
(1 row)
```

I'm closing the issue for now but please feel free to re-open it if necessary.

**Comment by psztoch** [comment]
> @psztoch OK, here is what happened.
> 
> Note that your argument is `2021-10-31 00:00:00+00'::timestamptz`. By specifying `+00` you overwrote the TZ.
timestamptz store data in UTC. When converting text to timestamptz, a zone must always be specified so that the example does not depend on the server zone.

This is basically an equivalent to `2021-10-31 00:00:00 UTC`, which is `2021-10-31 01:00:00 Europe/London`. Since time_bucket_ng() treats the argument in the provided timezone you got the result `2021-10-31 01:00:00`.
> 
> What you probably wanted to do was:
> 
> ```
> 40428 (master) =# SET TIME ZONE 'Europe/London';
> SET
> Time: 0.528 ms
> 40428 (master) =# SELECT timescaledb_experimental.time_bucket_ng('1 hour'::interval, '2021-10-31 00:00:00 Europe/London', 'Europe/London');
>      time_bucket_ng
> ------------------------
>  2021-10-31 00:00:00+01
> (1 row)
> ```
> 
> I'm closing the issue for now but please feel free to re-open it if necessary.

In my example there is no mistake and the given timestamptz in UTC clearly shows an error. Please analyze it yourself again and reopen ticket.
timebucket **cannot** return a time later than the timestamptz passed to it as an argument.

The timebucket function should ALWAYS return timestampt from the beginning of the bucket! Without it, the functionality of the functions is VERY limited in many applications.

Daylight saving time reveals additional problems that are not visible at first glance.
Unfortunately, DST is popular and, additionally, countries modify their time zones from time to time.

**Comment by afiskon** [comment]
@psztoch I believe there is a little misunderstanding in how timestamptz actually works.

Internally it is a time in UTC, the same as timestamp type. The only difference is how these types are displayed and converted from string. Basically timestmaptz is a timestamp that is displayed in the session timezone.

So what you are doing in your example is: taking a timestamp `2021-10-31 00:00:00 UTC`. Then saying to time_bucket_ng() to treat is in `Europe/London` timezone with the 3rd argument. OK, it's `2021-10-31 01:00:00 Europe/London`, no problem. Then you are asking which hourly bucket it is in the specified timezone. No problem, the bucket is `2021-10-31 01:00:00 Europe/London`, which is exactly the result you got:

```
=# SET TIME ZONE 'Europe/London';
SET

-- 2021-10-31 00:00:00 UTC == 2021-10-31 01:00:00 Europe/London
=# SELECT '2021-10-31 00:00:00+00' :: timestamptz;
      timestamptz
------------------------
 2021-10-31 01:00:00+01
(1 row)

=# SELECT timescaledb_experimental.time_bucket_ng('1 hour'::interval, '2021-10-31 00:00:00+00', 'Europe/London');
     time_bucket_ng
------------------------
 2021-10-31 01:00:00+00
(1 row)

-- same result
=# SELECT timescaledb_experimental.time_bucket_ng('1 hour'::interval, '2021-10-31 01:00:00 Europe/London', 'Europe/London');
     time_bucket_ng
------------------------
 2021-10-31 01:00:00+00
(1 row)
```

But THEN you are converting the result back to UTC and apparently expect it to be as if you specified 'UTC' as a 3rd argument of time_bucket_ng() instead of 'Europe/London'. If this is the case, I'm sorry, your expectations are wrong, `2021-10-31 01:00:00 Europe/London` is exactly `2021-10-31 01:00:00` UTC which again, is the result you got:

```
=# SELECT '2021-10-31 01:00:00 Europe/London' :: timestamptz AT TIME ZONE 'UTC';
      timezone
---------------------
 2021-10-31 01:00:00
(1 row)
```

I _suspect_ that maybe what you actually want is to convert timestamptz to timestamp with cutting-off the timezone. Unfortunately PostgreSQL can't do unless you specify the timezone, because again, internally timestamptz is the same timestamp in UTC, and PostgreSQL doesn't store the information about the timezone. So in this case you have to do `AT TIME ZONE 'Europe/London'`:

```
=# SELECT '2021-10-31 01:00:00 Europe/London' :: timestamptz AT TIME ZONE 'Europe/London';
      timezone
---------------------
 2021-10-31 01:00:00
(1 row)

=# SELECT timescaledb_experimental.time_bucket_ng('1 hour'::interval, '2021-10-31 01:00:00 Europe/London', 'Europe/London') AT TIME ZONE 'Europe/London';
      timezone
---------------------
 2021-10-31 01:00:00
```

For more information please address the PostgreSQL documentation https://www.postgresql.org/docs/current/datatype-datetime.html As you correctly pointed out, this is a tricky topic indeed, thus attention is advised. And you only scratched the surface of the complexity - there are historical timezones corrections, changes in the DST rules, function volatility, etc. We invested a lot of effort into implementing this feature correctly and testing it properly.

**Comment by afiskon** [comment]
> Well just no!

I would ask you to elaborate on this objection :) This is literally what time_bucket_ng() does. Trust me, I wrote it :)

```
Time: 2021-10-31 01:00:00 [Europe / London] has an ambiguous meaning.
We actually have two different times:
2021-10-31 01:00:00+01 [Europe/London] and
2021-10-31 01:00:00+00 [Europe/London].
```

You see, this is the reason of your confusion.

The is no double meaning of `2021-10-31 01:00:00 Europe/London`, not from PostgreSQL's perspective. This is an exact UTC time:

```
=# SET TIME ZONE 'UTC';
SET

=# SELECT '2021-10-31 01:00:00 Europe/London' :: timestamptz;
      timestamptz
------------------------
 2021-10-31 01:00:00+00
```

Also, there is simply no such thing as `2021-10-31 01:00:00+01 Europe/London`, again, from PostgreSQL perspective. You can't specify the timezone twice, it's either '2021-10-31 01:00:00 Europe/London` or `2021-10-31 01:00:00+01`, both are exact UTC timestamps.

I understand this can be contradicting to the normal person, but this is how PostgreSQL works with timezones, and we have to be consistent with how PostgreSQL does this.

**Comment by psztoch** [comment]
Processing the time in the format 2021-10-31 01:00:00 Europe / London is incorrect because it is ambiguous.
We actually have two different times:
2021-10-31 01:00:00+01 [Europe/London] and 2021-10-31 01:00:00+00 [Europe/London].
PostgreSQL perfectly interprets both of them. Both times have different real time (the one in UTC).

P.S. An additional problem is the lack of a function in postgres to add timestamptz and interval for a given time zone.
