### ISSUE TITLE
[Bug]: debian installation failure

### ISSUE THREAD

**Issue by DeoLeung** [timescale/timescaledb#4445]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Packaging

### What happened?

we install it through apt
```bash
# it used to work
apt-get install timescaledb-2-postgresql-13='2.6.1*'

# after 2.7 release, it seems to install a different version 'loader'
Setting up timescaledb-2-loader-postgresql-13 (2.7.0~debian11) ...
Setting up timescaledb-2-postgresql-13 (2.6.1~debian11) ...
```

it then cause error in `create extension`
```bash
extension "timescaledb" has no installation script nor update path for version "2.7.0"
```

maybe add some dependency for that, now I explicit install the `loader` package of `2.6.1`
```bash
apt-get install timescaledb-2-loader-postgresql-13='2.6.1*'
```

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

13.7

### What operating system did you use?

debian bullseye

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
apt-get install timescaledb-2-postgresql-13='2.6.1*'
```

**Comment by konskov** [comment]
Thanks for the bug report @DeoLeung , I was able to reproduce this too.

**Comment by konskov** [comment]
Hi @DeoLeung, if you are not installing the latest version (currently 2.7.0) you will need to specify the loader version as well to match the extension version. So the following command works for installing 2.6.1 specifically: 
```
apt-get install timescaledb-2-postgresql-13='2.6.1*' timescaledb-2-loader-postgresql-13='2.6.1*'
```

**Comment by perlun** [comment]
@konskov I ran into this now as well, but I would actually consider this a bug in the TimescaleDB packaging. The `Depends:` setting in this package is actually incorrect:

```
$ apt-cache show timescaledb-2-postgresql-13=2.9.3~ubuntu22.04
Package: timescaledb-2-postgresql-13
Priority: optional
Section: database
Installed-Size: 99913
Maintainer: Timescale <hello@timescale.com>
Architecture: amd64
Version: 2.9.3~ubuntu22.04
Depends: timescaledb-2-loader-postgresql-13 (>= 2.9.3~), postgresql-13 (>= 13.4), libc6 (>= 2.14), libpq5 (>= 9.2~beta3), libssl3 (>= 3.0.0~~alpha1)
Recommends: timescaledb-tools, timescaledb-toolkit-postgresql-13
Filename: pool/jammy/main/t/timescaledb-2-postgresql-13/timescaledb-2-postgresql-13_2.9.3~ubuntu22.04_amd64.deb
Size: 13220520
MD5sum: 5f3cc0d874a35af52452bcf14be79ac6
SHA1: b615f4a90b9e236fb712edf4f2cda22a2a35510b
SHA256: 03547c406b935e3a6ee4621d316640307227b6c229b0ec12371279a77ce5cb97
SHA512: a7425c0fc19881d224a038f2dd125ed748c18202d2ffa26df4e89ff4ae008f80076e0acb0514431e8de66e53ca6e095ef5f8f01d5e3a6d25a1f80728f6c48d46
Description: An open-source time-series database based on PostgreSQL, as an extension.
 An open-source time-series database optimized for fast ingest and complex queries.
 Engineered up from PostgreSQL, packaged as an extension.
Description-md5: b97777fcbb19d8fa967dc5865888b891
Homepage: https://timescale.com
```

The problem is with the `timescaledb-2-loader-postgresql-13 (>= 2.9.3~)` specifier. This should rightfully be something like `timescaledb-2-loader-postgresql-13 (= 2.9.3~ubuntu22.04)` instead, since there is a very strict requirement on a **specific** loader package version. If the package dependencies would be fixed here, it would ease the burden on people wishing to install a specific TimescaleDB version and reduce similar problems in the future.

Can we reopen this issue or do you want me to create a new issue for this, so we can discuss this further? I'm fine either way.
