### ISSUE TITLE
Timescale Docker Container max_wal_size

### ISSUE THREAD

**Issue by SimplySeth** [timescale/timescaledb#452]
Is there a way to set `max_wal_size` in the docker container?

If so, what is a good value to set it at? 

I'm seeing the below in splunk:

`LOG:  checkpoints are occurring too frequently (15 seconds apart)`

`HINT:  Consider increasing the configuration parameter "max_wal_size".`

**Comment by mfreed** [comment]
There are several ways to modify the config setting inside the docker container.  In the following examples, I use a docker container name of `timescaledb`.  As to what "value" is good to set at, this depends a bit on your setup and ingest rates.  If you are getting this error, I'd try doubling it (if you have enough storage) and see how that works.

Modify postgresql.conf
---

1. Get into a shell in docker in order to change the configuration on a running container.
```
docker start timescaledb
docker exec -i -t timescaledb /bin/bash
```
2. Edit and then save the config file, modify the setting for `max_wal_size`
```
vi /var/lib/postgresql/data/postgresql.conf
```
3. Restart the container so the config gets reloaded
```
docker restart timescaledb
```

4. Test to see if the change worked.  In this example, I increased the WAL size from 1GB to 2GB.
```
docker exec -it timescaledb psql -U postgres

postgres=# show max_wal_size;
 max_wal_size 
--------------
 2GB
```

Pass in options during boot
---

You can also specify different configuration commands in your docker run command:
```
docker run -i -t timescale/timescaledb:latest-pg9.6 postgres -cmax_wal_size=2GB
```
Note you can find more pointers to this in our discussion about using WAL-e:  http://docs.timescale.com/v0.8/using-timescaledb/backup#docker-wale

**Comment by mfreed** [comment]
Do you have any other questions @SimplySeth ?  Otherwise, I'll go ahead and close the issue.

**Comment by RobAtticus** [comment]
I'm going to close this, but feel free to re-open if you are still having issues @SimplySeth
