### ISSUE TITLE
[Bug]: OOM condition when loading large data set in to hypertable

### ISSUE THREAD

**Issue by ninjaltd** [timescale/timescaledb#4576]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

Inserting a large sized data set into a hypertable triggering a memory leak and causes system to go OOM.
Please refer issue #4560.  Upgrading to 2.7.2 did not fix this but the issue got closed.  So I am opening a new one.

### TimescaleDB version affected

2.7.2

### PostgreSQL version used

14.4

### What operating system did you use?

Debian GNU/Linux 11

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
n/a
```

### How can we reproduce the bug?

```bash
CREATE DATABASE test;
\c test
CREATE TABLE inet_session_usages (
    id bigint NOT NULL,
    inet_session_id integer NOT NULL,
    bytes_in bigint,
    bytes_out bigint,
    created_at timestamp with time zone,
    year_created integer,
    month_created integer,
    day_created integer,
    hour_created integer,
    minute_created integer,
    created_at_svc_tz timestamp without time zone
);
SELECT create_hypertable('inet_session_usages', 'created_at_svc_tz', chunk_time_interval => INTERVAL '1 day');
create unique index inet_session_usages_session_id_idx on inet_session_usages (created_at_svc_tz DESC, inet_session_id);

wget -O - https://tyl.spirit.net.au/~z/inet_session_usages.sql.xz | xz -d | psql test
```

**Comment by ninjaltd** [comment]
Sorry should have been:  

wget -O - https://tyl.spirit.net.au/~z/inet_session_usages.sql.xz | xz -d - | psql test

**Comment by mrksngl** [comment]
I likely hit the same issue.

I inserted 170GiB data using `COPY ... FROM STDIN WITH BINARY`.

For reference, I tried this with normal postgres, including the indexes which are normally created by timescale. This peaked at around 1.38GiB memory.

Doing the same with timescale, memory consumption rises in huge steps and I get an OOM kill before data is fully copied. Depending on the memory limit (postgres runs inside a kubernetes pod), it can take more or less data, but even 8GiB of memory were not enough to copy the data -- it stopped when roughly 120GiB was transferred.

@ninjaltd also pointed out issue #4650, but different from there I get the same behavior whether space partitioning is used or not.

I also ran into the following two interesting facts:
1) This also happened on the access node of a multi datanode cluster, where the access node should (in my understanding) only be responsible for offloading data to the respective data nodes.
Both setups (one distributed, one not) resulted in OOMs, the only difference I saw is, that when it's distributed, memory requests are done in very discrete steps, like allocating another GiB every five minutes. When it's not distributed, memory consumption rises more linearly.
2) When not having a distributed setup and the OOM happens, postgres restarts and recovers. As expected, the destination table is still empty. But: the disk space is not reclaimed. `pg_database_size` as well as `du` on the disk agreed that somewhat 70GiB were in use. Dropping the table (the only table in this DB) does not help, neither does restarting postgres. I had to drop the whole database in order to get those 70GiB deleted. I don't know whether this is an issue of timescale or of postgres itself. When I know more, I will open another issue (here or at postgres).

**Comment by mrksngl** [comment]
Another follow up: actually it only happened when the table was empty.

After I successfully copied the data (using the high memory limit), I inserted more data (an even larger dataset than the first one), again using `COPY`. I also restarted the access node and copied even more data afterwards.

Memory did not rise significantly, neither during the second copy (before the restart) nor the third (after the restart).
