### ISSUE TITLE
[Bug]: Real Time Aggregate not working

### ISSUE THREAD

**Issue by mmkim801** [timescale/timescaledb#4909]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Real-time aggregation is not working after dropping and recreating with the same view name.
The continuous aggregate has a specific time window with a start and end date. We refresh outside the continuous aggregate time window, which doesn't contain any data so real-time aggregation for the most recent data works. Here is what we get when we run this command line `EXPLAIN SELECT * FROM <view>`. Initially, we only want the data from the source hyper table.

![Screen Shot 2022-11-01 at 3 46 39 PM](https://user-images.githubusercontent.com/16828582/199356387-b6c387a4-a8a5-4822-91a3-a31cd87d35f8.png)

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Mac OS big sur

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Drop the existing materialized view and recreate it with the same name with a time window (e.g. start = 2022/11/04). Refresh with a date in the past (e.g. start = 2022/10/01 & end = 2022/10/15). Add recent data. Check aggregate. It wouldn't include the most recent data.
```

**Comment by konskov** [comment]
Hi @mmkim801, thank you for reaching out.

It is not clear to me what exactly is occuring here. It would be most helpful if you could provide a reproduction example with the exact steps you have followed, (how you created the continuous aggregate, what it is that you expected to see at each step...)

Thank you!

**Comment by mmkim801** [comment]
1. created a materialized view with timescaledb.continuous (`WHERE time >= '2022-11-28T23:22:05.581+00:00'
AND time < '2022-12-30T23:22:05.602+00:00'`)
2. added a continuous aggregate policy (`start_offset => NULL, end_offset => INTERVAL '2880 min', schedule_interval => INTERVAL '1440 min'`)
3. refreshed continuous aggregate (`CALL refresh_continuous_aggregate('view', '2022-11-24T23:20:56.416Z', '2022-11-26T23:20:56.416Z');`). 
4. dropped this materialized view
5. recreated it by repeating steps 1, 2, and 3.

When I first created the view, the real-time aggregation worked, but when I dropped it and recreated the exact same view real-time aggregation stopped working. The results of `EXPLAIN SELECT * FROM <view>` are also different.

<First created Materialized View Explain Result>
![Screen Shot 2022-11-29 at 10 13 46 AM](https://user-images.githubusercontent.com/16828582/204620656-0534cbc7-c4d7-45cd-a5a9-e3dee246b75a.png)

<Recreated Materialized view>
![Screen Shot 2022-11-29 at 10 16 03 AM](https://user-images.githubusercontent.com/16828582/204620806-d317761c-8714-413f-a65f-a421fcb2038e.png)

**Comment by mkindahl** [comment]
Hi @mmkim801!

It is unfortunately not very clear what you expect as output.

In the two screen-shots you have:

- the first one ([Screen Shot 2022-11-29 at 10 13 46 AM](https://user-images.githubusercontent.com/16828582/204620656-0534cbc7-c4d7-45cd-a5a9-e3dee246b75a.pngl)) a real-time aggregate to create the full view, which means that the materialized table is not used, and
- in the second one ([Screen Shot 2022-11-29 at 10 16 03 AM](https://user-images.githubusercontent.com/16828582/204620806-d317761c-8714-413f-a65f-a421fcb2038e.png)) uses the materialized hypertable to avoid re-computing some buckets, which is probably because the refresh policy has executed.

So in both cases, real-time aggregates are used.

>  It seemed like if I don't stop the real-time aggregation, it uses the same hypertable.

Not sure what you mean with this. If you re-create the continuous aggregate, it should read from the same hypertable in both cases, i.e., `program_events` in your case.
