### ISSUE TITLE
[Question]: <The default value of timescaledb.max_background_workers shows different value in 2 places of doc>

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5055]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

Hello,

The default value of timescaledb.max_background_workers shows different value in 2 places of doc

timescaledb.max_background_workers (int)
Max background worker processes allocated to TimescaleDB. Set to at least 1 + number of databases in Postgres instance to use background workers. Default value is 16
https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-config/

By default, timescaledb-tune sets timescaledb.max_background_workers to 8
https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/about-configuration/

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Centos 7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
N.A
```

**Comment by sb230132** [comment]
Hi @yinan8128 
Thanks for reporting this issue. I checked with @konskov and the right default value should be 16. We will make necessary changes to make it consistent.

**Comment by konskov** [comment]
hi @yinan8128 thank you for reporting the discrepancy. The default value should be 16 for both. We will update both the documentation and timescaledb-tune (https://github.com/timescale/timescaledb-tune/pull/112) soon. In the meantime, I would recommend explicitly setting the number to 16 (`timescaledb-tune --max-bg-workers=16`) 
I will go ahead and close the issue since there is a PR to fix it.
