### ISSUE TITLE
Order of insert

### ISSUE THREAD

**Issue by joethong** [timescale/timescaledb#508]
Hi,

Is the order of insert into the hypertable an important issue to be optimized for SELECT queries?  Is it best to keep the data inserted at a chronological order?  The reason I'm asking is we are fetching data for different timeranges in parallel, do we need to ensure that the data to be sorted chronologically before bulk inserting into timescale?  Or will the INDEX take care of this?  

Thank you in advance.  

Regards
Joe

**Comment by mfreed** [comment]
Data should be *loosely* ordered by time on insert, in order to achieve high insert rate (this has no effect on query performance), such that inserts are typically to the latest (or two) chunks.   

For example, if you have a chunk interval of 1 day, you'd want to make sure that most of your inserts are to Apr 1, then Apr 2, then Apr 3, and so forth.  If the interval is 1 hour, you want your inserts to mostly be to 12-1pm, then 1-2pm, etc.  This ensures that the chunks being inserted to are largely in memory, and so you aren't constantly swapping back-and-forth to disk at insert time, which would happen if your insert's timestamps are randomly distributed over the year.  A deeper explanation of why is given here:  https://blog.timescale.com/time-series-data-why-and-how-to-use-a-relational-database-instead-of-nosql-d0cd6975e87c

That said, no matter how the inserts are performed (either in-order or out-of-order), they are inserted in the correct chunk and, if an INDEX exists, the index is properly built over their timestamp.  So your query (SELECT) performance isn't affected by the ordering of inserts.

**Comment by joethong** [comment]
thank you @mfreed , this clears things up immediately!

**Comment by m2b** [comment]
I know this is a closed issue but I could use some explanation of what I am observing.  Chunk ranges are 7 days,  Sizes are about 1.5 GB.  One of my IoT sites lost connection for a day or so and upon restoring the connection it started sending cached data which is "out of order" versus data from other sites which never lost connection.   Data is being sent in order but is not most recent timestamps.  The data is 1 day old and all within the most recent chunk.   The insertion time for 50 records went from milliseconds to over 1 minute.  So slow that it may never catchup as more data is being cached locally.  The TimescaleDB server CPU and memory did not seem impacted.  What do you recommend?  Greatly appreciated.  Some questions in my mind: 1. Should I make the chunk sizes smaller?   2. Does the time to insert become worse as the data is older.  That is will it be faster to insert more recent values.  3.  Is this big chunk perhaps not in memory or not all in memory.  How do I check?

**Comment by m2b** [comment]
@mfreed can you provide me some input?

**Comment by akuzm** [comment]
@m2b do you have a compression policy enabled? Following this procedure for backfilling into compressed tables may help: https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/backfill-historical-data/

A better place for such questions is the community forum or slack: https://www.timescale.com/community

**Comment by m2b** [comment]
Hi @akuzm thanks for the recommendation.  We are targeting for keeping 30 days raw data and aggregating as well.  Since I have a version supported by a third party (aiven.io), the aggregation strategy recommended is not supported.
