### ISSUE TITLE
set_chunk_time_interval 

### ISSUE THREAD

**Issue by tkald** [timescale/timescaledb#542]
Hi,

seems to me that after changing the chunk interval of hypertable, no new chunks are created.

Here's my case - initially I created time slice too big:

`SELECT create_hypertable('history_new', 'clock', chunk_time_interval => 86400000);`

Since my date field is INT and data is stored in seconds, not milliseconds (since epoch) - I created hypertable chunk interval by mistake for 1000 days instead of 1 day.

So I altered hypertable:
`SELECT set_chunk_time_interval('history', 86400);`

Before hypetable alteration, table was renamed to "history" (if it's relevant).

Several days have passed by and I don't see any new chunks created with query:
`SELECT * FROM _timescaledb_catalog.chunk`

Postgresql 10.3 and Timescaledb 0.9

**Comment by mfreed** [comment]
This function changes the time interval for *future* chunks, it does not alter *existing* chunks.  If your initial chunk was for 1000 days, it probably stretches far into the future.

To test this, can you perform an INSERT with some timestamp that's more than 1000 days in the future?

**Comment by tkald** [comment]
I see. I allready recreated tables with correct chunk interval. So problem solved :)

**Comment by vfvgc** [comment]
I've made the same mistake as the original creator of this issue.  
(Namely: due to ms/µs confusion, I've set the chunk interval to 1000 weeks instead of 1 week.)

It seems this kind of a mistake paints the user into a corner. I've updated the chunk interval, but the change won't actually come into effect for another decade or two.

Is there any reasonably straightforward way to fix this without destroying all the tables?
