### ISSUE TITLE
Timed out waiting for server startup. on windows 7 x64

### ISSUE THREAD

**Issue by maxiwu** [timescale/timescaledb#548]
install the latest postgresql 10.4. follow the setup guide.
turn off postgresql, modify conf file [shared_preload_libraries = 'timescaledb']
then try to turn postgresql back on, fail with this error.

```
2018-05-29 17:56:24.474 CST [195088] FATAL:  could not access file "timescaledb": No such file or directory
```

if 'timescaledb' is installed as an extension, it fails. \dx shows only two 'adminpack' and 'pbpgsql'

**Comment by RobAtticus** [comment]
Have you made sure that the C++ Redistributable is installed?

**Comment by maxiwu** [comment]
yes, I carefully follow installation steps official document. [https://docs.timescale.com/v0.9/getting-started/installation/windows/installation-windows](url)

But I do not know what "Make sure all relevant binaries are in your PATH: (use pg_config)" this means.
what are the relevant binaries?

**Comment by RobAtticus** [comment]
Hmm, appears to be a typo, should be `e.g.` instead of `use`. `pg_config` needs to be in your Windows PATH environmental variable in order for installation to complete successfully. Typically this means that your PATH includes something like `C:\Program Files\PostgreSQL\10\bin\` or whatever the path to the `bin` folder is for PostgreSQL. Does yours?

The installer should show an error if not. Can you check that timescaledb.dll is in your PostgreSQL's `lib` folder?

**Comment by maxiwu** [comment]
you are right. I checked my \10\lib, there is not timescaledb.dll in it. Then I check my PATH, I've a previously installed PostgreSQL 9.4 path in it. I change it to the new PostgreSQL 10 path and problem is solved.

**Comment by RobAtticus** [comment]
Great, glad to hear it!

**Comment by zcattacz** [comment]
Thanks, I bump into the same issue. But in my case, it's `anconda`.  causing the problem. I have to `conda deacivate` before execute timedb's `setup.exe`, or all the paths in `pg_config.exe` output  point to anaconda's directory, not postgresql's.
