### ISSUE TITLE
[Bug]: rolling up chunks into a larger compressed chunk takes a long time

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [timescale/timescaledb#5612]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression

### What happened?

When rolling up multiple chunks into one larger chunk (e.g. `14 x 12 hours` → `1 x 7 days`), the compression duration and temporary space requirements increase with each chunk that gets merged into the compressed chunk.

This chart shows the compression of 12 hour chunks (~9 GB each) into 7 day chunks. It looks like each chunk that gets added needs to re-compress everything that was already compressed.
![image](https://user-images.githubusercontent.com/15961647/234303945-11c25c87-7c5c-4aef-ac8f-81bae26d032a.png)

Would it be possible to compress all chunks that belong to a compressed chunk at once, instead of one-by-one?

This behaviour makes backfilling data very slow, as compression can't keep up with the ingest rate. It also causes more blocked queries (as explained in #2732)

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

### What operating system did you use?

Ubuntu 22.04.1 LTS (amd64)

### What installation method did you use?

Other

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
Set `compress_chunk_time_interval` to a multiple of `chunk_time_interval` and compress chunks.
```

**Comment by konskov** [comment]
hi @SoMuchForSubtlety, thank you for reaching out. I’d like to ask what is your hypertable and compression configuration? (more specifically, the number of dimensions on your hypertable and chunks, and the segmentby and orderby configuration for compression)
I suspect this is because of the recompression step at the end of merging the compressed chunks, in case the produced chunk is unordered (https://github.com/timescale/timescaledb/blob/main/tsl/src/compression/api.c#L555) 
The team is actively working on improvements in several areas of compression, including making recompression faster (commit https://github.com//timescale/timescaledb/commit/72c0f5b25e569015aacb98cc1be3169a1720116d was a first step in that direction)

**Comment by SoMuchForSubtlety** [comment]
The hypertable in question has no additional dimensions, just time. For compression, we also just use the default time ordering, and segment by three columns.

We get a compression rate of ~90-95%

**Comment by konskov** [comment]
Hmm if you are not using additional dimensions other than time, then it sounds like there’s no need for recompression...
It would be ideal if we could reproduce this behavior locally to investigate it further. So yes please provide your exact setup, as it would be a great help in reproducing and understanding the issue you are facing. Thank you!

**Comment by konskov** [comment]
Thank you for your help @SoMuchForSubtlety.  It seems recompression is still the issue here, as compressed data is first sorted, then stored in that order, and the default ordering is DESC. However chunks are merged by time ASC, so the produced chunks would still be unordered and require recompression, unless you specify an ASC orderby. So in your compression settings, could you set `compress_orderby='time ASC'`? I expect that would solve the problem.

**Comment by SoMuchForSubtlety** [comment]
What effect will modifying the compression settings have on already compressed chunks? Should I re-compress them?

**Comment by SoMuchForSubtlety** [comment]
The issue is no longer present with `compress_orderby='time ASC'`, thanks for the help.
