### ISSUE TITLE
[Bug]: Performance issues after docker upgrade

### ISSUE THREAD

**Issue by muntdan** [timescale/timescaledb#5799]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Data ingestion, Query executor, Query planner

### What happened?

I am writing a lot of data into a local timescaledb docker with mounted volumes and whose tables are sharded by 7days interval and 10 tenants(secondary dimension).
Writes: 2 tables 1K rows/sec, 2 tables: 0.75K rows/sec, 1 table 0.5K rows/sec, 2 tables 0.4K rows/sec, 6 tables: 0.03K rows/sec.
Reads are being done seldom and not on big intervals/data.

Normal KPI Usage : 0.5 CPU of 1 CORE (out of 24) / 32 GB RAM (out of 64).
All writes operations (on multiple tables at once) have durations < 10ms. All reads have durations < 40ms.

Whenever I upgrade the docker and restart the RAM usage ofcourse goes to 0, and than start to slowly increase.
The problem is that for a few hours there are spikes in durations: some reads /writes goes to seconds duration and some reads up to 1 minute.
I suspect there are internal jobs running and they might be the cause.
It does not start to degrade until I do the final step of actual extension upgrade: `ALTER EXTENSION timescaledb UPDATE;`

After this few hours, I can restart the docker multiple times and although RAM goes to 0 again, the performance is normal after each restart with no degradation anymore.

This happened to me on both 2.9.3 upgrade to 2.11.0 but previously also from 2.8.1 to 2.9.3.

### TimescaleDB version affected

2.11.0

### PostgreSQL version used

15.3

### What operating system did you use?

Ubuntu 22

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
I imagine you need to have some large enough existing tables/data so on upgrade you are starting with existing volume/data attached.
```

**Comment by lkshminarayanan** [comment]
Hi @muntdan,

Thank you for filing the issue!

When you do an upgrade, the internal tables and other objects maintained by the extension could undergo changes like getting a new column, getting a new index, drop an old column etc., to support the new features added to the newer version. This is triggered by the `ALTER EXTENSION timescaledb UPDATE;` statement and probably that is the work consuming more of your RAM when you do an upgrade. 

For example, when you upgraded from 2.8.1 to 2.9.3, version `2.9.0` introduced a bunch of features due to which we had to update our internal catalog definitions. (You can view the complete list of changes made to the internal catalog objects here - [2.8.1--2.9.0.sql](https://github.com/timescale/timescaledb/blob/71f07801a6e88d019f1835abc247c612375a3f3a/sql/updates/2.8.1--2.9.0.sql)).

It is possible that some of these upgrade statements were conflicting with your transactions causing a delay in your read/writes as the read/writes to hypertables might have to lookup and update some of these internal catalog tables as well. The transactions you run might slow down the upgrades as well. 

The next time you do it, I would recommend upgrading the extension during a time when there is low activity in the database, so that upgrades are not slowed down and you also have a less chance of seeing performance degradation. Apart from this, I do not think cause for concern as the performance was back to normal post upgrade. Please let me know if you need more information on this.
