### ISSUE TITLE
[Bug]: hypertable_size is really expensive for large hypertables

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#6006]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Command processing

### What happened?

When running `hypertable_size` on really large tables it can become excessively expensive. In particular for tables with a large number of chunks. In particular, when chunk sizes do not change for anything but the most recent chunks.

### TimescaleDB version affected

2.12.0

### PostgreSQL version used

15.3

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE conditions(
    time timestamp with time zone NOT NULL,
    device_id INTEGER,
    temperature FLOAT,
    humidity FLOAT
);

SELECT * FROM create_hypertable('conditions', 'time', chunk_time_interval => '1 hour'::interval);

INSERT INTO conditions
SELECT time, (random()*3 + 1)::int, random()*80 - 40, random()*100
FROM generate_series(now() - INTERVAL '2 years', now(), '1 minute') AS time;

SELECT hypertable_name, hypertable_size(format('%I', hypertable_name)::regclass)
FROM timescaledb_information.hypertables;
```

```[tasklist]
### Tasks
- [ ] https://github.com/timescale/timescaledb/pull/6463
```

**Comment by fabriziomello** [comment]
@mkindahl not sure if we'll have a big gain rewriting it in C since the real problem is the underlying `_timescaledb_functions.relation_size` function calls that rely on the Postgres internal function `pg_total_relation_size`  that read the size information by calling the [`stat` system call](https://en.wikibooks.org/wiki/C_Programming/POSIX_Reference/sys/stat.h/stat).

Other idea is implement a variation of this function to do an approximate calculation of the relations using the `pg_class.relpages` (more or less this POC - https://github.com/fabriziomello/timescaledb/commit/3afbf901d658bc31a227a13d07fb5ccb6bf22983), but I found a problem that the relpages for the toast index is not updated. I've [sent a message about it to pgsql-hackers](https://www.postgresql.org/message-id/CAFcNs%2BoLVK7LPYAweH%3DMXb9cKQKgoO9LkornjjeHnA%3D2SwfeoA%40mail.gmail.com) but didn't received any answer yet.
In any case with the current situation I was able to tweak a bit Postgres to make this calculation a bit faster, have a look in the example below:
```sql
452071 (leader) fabrizio=# SELECT hypertable_name, hypertable_size(format('%I', hypertable_name)::regclass)
FROM timescaledb_information.hypertables;
 hypertable_name | hypertable_size 
-----------------+-----------------
 conditions      |      1004732416
(1 row)

Time: 857,838 ms
452071 (leader) fabrizio=# ALTER FUNCTION _timescaledb_functions.relation_size(REGCLASS) STABLE PARALLEL SAFE ROWS 1;
ALTER FUNCTION hypertable_size(REGCLASS) STABLE PARALLEL SAFE;
ALTER FUNCTION hypertable_detailed_size(REGCLASS) STABLE PARALLEL SAFE ROWS 1;
ALTER FUNCTION _timescaledb_functions.hypertable_local_size(name, name) STABLE PARALLEL SAFE ROWS 1;
ALTER FUNCTION
Time: 48,748 ms
ALTER FUNCTION
Time: 28,435 ms
ALTER FUNCTION
Time: 27,730 ms
ALTER FUNCTION
Time: 27,852 ms
452071 (leader) fabrizio=# SELECT hypertable_name, hypertable_size(format('%I', hypertable_name)::regclass)
FROM timescaledb_information.hypertables;
 hypertable_name | hypertable_size 
-----------------+-----------------
 conditions      |      1004732416
(1 row)

Time: 584,942 ms
``` 
This small changes decreased the total time from 857,838 ms to 584,942 ms ~32% performance improvement.

**Comment by nikkhils** [comment]
Draft PR for this https://github.com/timescale/timescaledb/pull/6463
