### ISSUE TITLE
[Enhancement]: Make _timescaledb_internal.cagg_watermark PARALLEL SAFE

### ISSUE THREAD

**Issue by snyrkill** [timescale/timescaledb#6194]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Continuous aggregate

### What does the enhancement do?

I was wandering why querying my CAggs never involved any parallelism.
As you know, Timescale adds the clause
`COALESCE(_timescaledb_internal.to_timestamp_without_timezone(_timescaledb_internal.cagg_watermark(28)), '-infinity'::timestamp without time zone)` to the view definition.
Selecting from the CAgg shows no parallelism until the function `_timescaledb_internal.cagg_watermark` is altered to PARALLEL SAFE. 
```
postgres@ut-pgsql-t02:~/sql$ echo "explain select count(*) from ath.sj_klst_new"|psql mydb|grep Parallel|head -20
postgres@ut-pgsql-t02:~/sql$ echo " alter function _timescaledb_internal.cagg_watermark parallel safe"|psql mydb
ALTER FUNCTION
postgres@ut-pgsql-t02:~/sql$ echo "explain select count(*) from ath.sj_klst_new"|psql mydb|grep Parallel|head -20
                     ->  Parallel Custom Scan (ChunkAppend) on _materialized_hypertable_28  (cost=0.00..537751.81 rows=6533005 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1878_chunk  (cost=0.00..78796.24 rows=946528 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1877_chunk  (cost=0.00..74871.15 rows=901894 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1876_chunk  (cost=0.00..72602.76 rows=868158 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1875_chunk  (cost=0.00..71330.49 rows=854771 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1874_chunk  (cost=0.00..69510.08 rows=829319 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1873_chunk  (cost=0.00..68121.40 rows=808137 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1879_chunk  (cost=0.00..65030.56 rows=783175 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1872_chunk  (cost=0.00..36843.66 rows=527923 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1881_chunk  (cost=0.00..611.82 rows=12732 width=101)
                           ->  Parallel Seq Scan on _hyper_28_1882_chunk  (cost=0.00..11.65 rows=31 width=468)
                           ->  Parallel Seq Scan on _hyper_28_1883_chunk  (cost=0.00..11.65 rows=31 width=468)
                           ->  Parallel Seq Scan on _hyper_28_1880_chunk  (cost=0.00..10.36 rows=306 width=103)
```
This select runs twice as fast with parallel safe (16 vs 32 secs). 
The function `_timescaledb_internal.cagg_watermark_materialized ` is parallel safe so this should be possible?
Will altering the function in it's current state break anything?

**Comment by jnidzwetzki** [comment]
Hello @snyrkill,

Thanks for reaching out. The `cagg_watermark_materialized` function is not marked as `PARALLEL SAFE` at the moment since this could lead to problems. If the function were marked as parallel safe, it could be executed by different parallel workers, and it could return different results for each of these workers. This disagreement about the watermark value could result in crashes and unexpected query results.

However, with #6325 we introduce the constification of this function call at plan time. Since the actual function invocation is removed from the query plans, the generated plans could be [executed using parallel workers](https://github.com/timescale/timescaledb/pull/6325/files#diff-237f415994894f9e590695a7cd29bcb5a0e183e6852629f249030aa31833e4c7R2280) (if no other non-parallel safe functions are used). It means after this change is merged into TimescaleDB, you should get parallel plans for real-time CAggs even if the watermark function is still marked as `PARALLEL RESTRICTED`.

**Comment by snyrkill** [comment]
Thank you @jnidzwetzki. 
This is great news. 
Do you know if there are any plans to allow parallel workers when creating (or refreshing) CAggs?

**Comment by jnidzwetzki** [comment]
Hi @snyrkill,

We have discussed this enhancement internally for some time already. I have created issue #6565 to track the work around this.
