### ISSUE TITLE
Documentation is wrong for chunk_time_interval in some places.

### ISSUE THREAD

**Issue by rockstarapps** [timescale/timescaledb#620]
On the page https://docs.timescale.com/v0.9/api#create_hypertable, there are several places you have the value (86400000000) as an chunk_time_interval which is a 1000 bigger than 86400000 the number of milliseconds in the day.

**Comment by solugebefola** [comment]
Thanks for the info.  We have actually put the content for our docs up on Github here: https://github.com/timescale/docs.timescale.com-content with docs for each DB version in the branch of the same name.  If you are interested, you could put in a PR, otherwise we'll change it for the next update.

**Comment by mfreed** [comment]
Timestamps in Postgres are by default expressed in microseconds, not milliseconds:

https://www.postgresql.org/docs/9.1/static/datatype-datetime.html

So I believe that the docs in these examples are correct.  If your time column is a timestamp, you can set the chunk interval using a `interval` type or a numeric as expressed in **microseconds**.

If your time column is an integer, then you need to tell us the resolution that the integer represents (e.g., seconds, millis, microseconds, nanoseconds, etc.)

Please let me know if you notice anything else (I thought I checked this page you pointed to, and it looks correct).  Otherwise, let's close this issue out.
