### ISSUE TITLE
[Bug]: Wrong CMake minimum version

### ISSUE THREAD

**Issue by syvb** [timescale/timescaledb#6202]
The root `CMakeLists.txt` specifies a minimum CMake version of 3.10:

https://github.com/timescale/timescaledb/blob/9f84c98ac70f5442076927e481abafca7e1c1200/CMakeLists.txt#L1

But `sql/CMakeLists.txt` uses `list(PREPEND)`, which [was added in CMake 3.15](https://cmake.org/cmake/help/latest/command/list.html#prepend):

https://github.com/timescale/timescaledb/blob/9f84c98ac70f5442076927e481abafca7e1c1200/sql/CMakeLists.txt#L271

Either the minimum CMake version should be updated to 3.15 or the `list(PREPEND)` call should be updated to be compatible with older CMake versions.

(I ran into this while trying to build TimescaleDB on Debian 10 for Toolkit. Debian 10 is pretty old though so I might just drop support in Toolkit.)

**Comment by svenklemm** [comment]
The minimum required version is set to the minimum required version to successfully build timescaledb. Some targets might require a higher cmake version, but the version is installed set to the one required to build to allow successfully building on certain older platforms where that version is not easily available. If we want to raise that version we first have to check those older platform whether they now have that version available otherwise we will run into issues during next release when building packages.
