### ISSUE TITLE
[Enhancement]: Adding Elestio as deployment optionn in Readme

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [timescale/timescaledb#7218]
### What type of enhancement is this?

Other

### What subsystems and features will be improved?

Other

### What does the enhancement do?

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing TimescaleDB application as shown here. I think it would be a great idea if we can add it to official readme/documentation [here](https://elest.io/open-source/timescaledb).
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by SawyerHopkins** [comment]
You might want to check the licensing for this software.

https://docs.timescale.com/about/latest/timescaledb-editions/

**Comment by mfreed** [comment]
@kaiwalyakoparkar:

As @SawyerHopkins referenced, you should only be offering the Apache 2 Edition as part of a "database-as-a-service" offering; otherwise, this would violate the Timescale License

If you are, please also always refer to what you offer as "TimescaleDB Apache 2 Edition" in your documentation and marketing material, and not just "TimescaleDB", in order to avoid market confusion.

https://docs.timescale.com/about/latest/timescaledb-editions/

**Comment by kaiwalyakoparkar** [comment]
Hey @mfreed and @SawyerHopkins, Yes, we are offering Apache 2 Edition as part of a "database-as-a-service" offering. Thank you so much for the suggested updates, we will get our marketing materials & website updated accordingly. I would also appreciate if you can let me know if there needs to be any updates in the referred pull request? (I have changed the name and created a new pr as you suggested above)

**Comment by mfreed** [comment]
This isn't the type of information we include in our docs.
