### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alanhamlett** [timescale/timescaledb#732]
After installing timescale when I try to enable the extension I get this error:

```
# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
ERROR:  could not load library "/usr/lib/postgresql/10/lib/timescaledb-1.0.0-rc1.so": libssl.so.1.1: cannot open shared object file: No such file or directory
```

I've installed openssl v1.1.1 from source, maybe it's related?

**Comment by FlorianWendelborn** [comment]
I had a similar issue and in my case it was due to mounting a database generated by a different machine into the container. It worked fine with a clean database. Just in case anyone else runs into something similar:

```
ERROR: could not load library "/usr/local/lib/postgresql/timescaledb-2.8.1.so": Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/local/lib/postgresql/timescaledb-2.8.1.so)
```

Since this happened on a dev setup making a new DB was sufficient for me. Good luck if you landed here through a search engine
