### ISSUE TITLE
TimescaleDB 1.0.0-rc1 no update path from 0.12.1

### ISSUE THREAD

**Issue by maximshe** [timescale/timescaledb#748]
Hi folks,

I tried to update TimescaleDB from `0.12.1` to `1.0.0-rc1` and got this error:
```
ERROR:  extension "timescaledb" has no update path from version "0.12.1" to version "1.0.0-rc1"
```

**Comment by amytai** [comment]
Yeah, there's no update path from `0.12.1` to `1.0.0-rc1` since they are on separate release paths. If you're looking to try the release candidate, go ahead and check-out `1.0.0-rc1` directly. Next week, we plan to have a `1.0.0-rc2` release, which you can update from `1.0.0-rc1`. Otherwise, you're good with `0.12.1` right now. (I would recommend trying out `1.0.0-rc2` when we release next week :) )

**Comment by maximshe** [comment]
Ok, thank you.
