### ISSUE TITLE
Telemetry Causing Rollbacks

### ISSUE THREAD

**Issue by timolson** [timescale/timescaledb#757]
I wanted to be nice and leave telemetry running for at least my dev/staging environment, but this kind of this is completely unacceptable.  I'll be disabling telemetry everywhere:

```
LOG:  TimescaleDB background worker launcher connected to shared catalogs
WARNING:  could not make a connection to https://telemetry.timescale.com/v1/metrics
DETAIL:  Interrupted system call
WARNING:  could not make a connection to https://telemetry.timescale.com/v1/metrics
DETAIL:  Interrupted system call
LOG:  worker process: Telemetry Reporter (PID 639) was terminated by signal 11
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
```

**Comment by amytai** [comment]
Hi, @timolson -- we actually have a fix out for this issue, but totally understand you want a .. working backend. If you don't mind helping us investigate further, any idea why you can't connect to the telemetry endpoint? Did you expect this because you have network rules installed? The PR we have out prevents the crashing, but I'd still like to know why some people can't connect to the endpoint. Thanks!

**Comment by timolson** [comment]
I don’t mean to sound snarky and should have looked at other issues harder
first... Happy to help debug, but does it really matter why?  You can never
expect 100% connectivity.  The problem is intermittent for me and likely
just network congestion.

**Comment by amytai** [comment]
I totally agree with you (I mean, if you look at the fix, the problem is use-after-free, which is obviously a bug on our end). I'm just surprised I haven't seen this error earlier, since telemetry has been in the wild for a couple weeks now. Which is why I asked why you didn't have connectivity, since I'm actually wondering if there's something going on with our endpoint as well.

**Comment by timolson** [comment]
I'm a new user, only been running a stress test for less than 24 hours.

BTW, pretty happy so far with the performance.  Came here from InfluxDB which is a real pile.  Their key space can't handle large cardinality... WTF!!  I found it impossible to adequately model a simple table for financial trade data.  On the flip side, Timescale's lack of a storage engine with delta encoding ala Gorilla is really unfortunate.  Had to rethink some things to accommodate an extra order-of-magnitude for storage.  Sorry to drop extra comments in this issue, but while I have your ear... :)  Will close since this is a dupe.

**Comment by erinaceous** [comment]
> I'd still like to know why some people can't connect to the endpoint. Thanks!

In my kubernetes environment, alpine linux image based containers have trouble resolving domain names external to the cluster due to how CoreDNS sets its search paths by default:
https://github.com/kubernetes/kubernetes/issues/64924
(e.g. `ping other-service.namespace.svc.cluster.local` works but `ping google.com` returns NXDOMAIN)

As far as I can see, normal timescaledb docker image is based on postgres rather than postgres:alpine, but my timescaledb containers appear to not be resolving DNS:

    $ ping google.com
    ping: bad address 'google.com'

    $ ping 8.8.8.8
    PING 8.8.8.8 (8.8.8.8): 56 data bytes
    64 bytes from 8.8.8.8: seq=0 ttl=117 time=4.230 ms

The workaround in kubernetes that I've found is to, in my deployment spec:

      dnsConfig:
        options:
        - name: ndots
          value: "1"

This was a fun bug for me to track down as I've been running timescaledb 0.12 on our DB for quite a while and we've been mysteriously having txn rollbacks I haven't noticed :-)

**Comment by impredicative** [comment]
@timolson What are the steps for disabling telemetry? Thanks.
