### ISSUE TITLE
Timescaledb minimun chunk_time_interval

### ISSUE THREAD

**Issue by alzapataman** [timescale/timescaledb#826]
Hello,

I'm considering in using timescaledb for a customer PoC, wich has the following use case:

200 devices generated 3 metrics every 3 microseconds for 4 hours.

1 Hypertable with 100 billions rows.

My plan is set the chunk time interval to 1 minute, resulting in 240 total chunks for our 100 billions row dataset.

According to timescale ingest rate (120.000 rows/sec) it will take us more than 260 hours in a machine with 8 cores and 28 GB  Memory. 

Is there a way to scale out timescaledb across multiple nodes?

Thanks in advance

**Comment by dianasaur323** [comment]
@alzapataman I would encourage you to ask these types of questions in our Slack channel. Regarding chunk time interval, it depends on how large each row you are inserting is - you want your chunk to be roughly 25% of your total RAM (in this case, that would be around 7GB. If you expect one minute of data to be 7GB, then that would be the right chunk size. Otherwise, I would go slightly bigger. In this scenario, I would try to normalize things so that you can write more data in a row. Our benchmarks include 10 metrics in a row. So, in this case, you could store each second as an array of microseconds? How are you expecting to query this data?

**Comment by mfreed** [comment]
Hi @alzapataman did you find your questions answered?

**Comment by svenklemm** [comment]
Seems this question was answered so closing this, feel free to reopen if it wasnt sufficiently answered.
