### ISSUE TITLE
Centos 6.x

### ISSUE THREAD

**Issue by linuxmanxxx** [timescale/timescaledb#868]
Running from RPM vs compiling. I see there is a gcc compatibility with compiling. What is needed to get the rpm prebuilt to run on CentoOS 6.5 or >? CentOS 6 is fully supported on postgresql10 so why didn't you guys include it for timescale? There is no upgrade path on CentOS so that's really not an option in production land.

**Comment by RobAtticus** [comment]
We drew the line at CentOS 7 because that was the oldest version we found that we work with that didn't require installing packages outside of the standard repos. I believe it is possible to get working on CentOS if you download a sufficiently recent gcc (4.8+ I believe) but we just haven't heard a ton of demand for CentOS 6 so we haven't explored packaging our own version.

**Comment by linuxmanxxx** [comment]
I updated glibc to 2.17 and installed rpm gonna test it. Someone in fedora
epel built the packages 2 yrs ago and using many years of rpm skills I got
them in with very little pain. I think it will all go fine. If testing goes
well maybe you can put it on your wiki as unsupported but here's how.
Steve

**Comment by mfreed** [comment]
@linuxmanxxx Did the glibc resolve your issue and we should close it?

**Comment by linuxmanxxx** [comment]
It has performed quite well after the update. Someone in the fedora
packages for cents has all the glibc rpms already done. You can close it.
Steve
