### ISSUE TITLE
Apache vs Community Edition

### ISSUE THREAD

**Issue by pjebs** [timescale/timescaledb#963]
I can't find a list of the differences between the open-source apache version and the community edition.

Are there substantial differences?

**Comment by akulkarni** [comment]
Right now there are no differences (we have yet to release any community features). 

That said, we're already developing the first community features, which you can see out in the open in the `/tsl` folder. 

But once we do have community/TSL features that differentiate the community version from the Apache 2, you'll be able to see the comparison on this webpage: https://www.timescale.com/pricing (again, nothing there are the moment since there are no TSL features yet).

I am going to close this issue for now, but feel free to re-open if you have any questions.

Thanks!

**Comment by imswill** [comment]
I took a look at the comparison table in the webpage, but I couldn't clearly figure out what the difference is for continuous aggregations feature.

It says "Automatic continuous aggregations" is not available in Open-source version. Does this mean I can still create and use CA views but it should be refreshed manually? If so, what is the way to do it?

Do I need to create a trigger for insert/update/delete/truncate with "REFRESH MATERIALIZED VIEW"?

**Comment by imswill** [comment]
Please, any answer would be very appreciated

**Comment by bboule** [comment]
Hello @imswill  apologies for the late response... So you really have two options here you can use the OSS version (under the apache license) and you can write the code to create the view and the code to keep it up to date (triggering it with a background job) as the continuous aggregate function is not available in the OSS edition. This tends to be complex and you will need to maintain this code... or you can use the Community Edition and the function for creating the view will be available (Continuous Aggregates), and if you set it up according to our docs the software make sure it is kept up to date in the background (i.e. you will not have to worry about maintaining any of this through upgrades etc. we will handle all of this for you).  Hopefully that answers your question.

**Comment by imswill** [comment]
Thanks! This helps a lot.
